### ISSUE TITLE
Change chord length distribution

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#1]
Adjust CLD to show 'fraction larger than given size' (after Kaye)

**Comment by jgostick** [comment]
Or, use Matt's approach from his thesis

**Comment by mdrkok** [comment]
I've made function called chord_length_distribution_helper that is really just a wrapper for the simplest version of cld's. It takes the binary image and returns three 1d arrays representing the weighted chord length distributions.

**Comment by mdrkok** [comment]
I'd be happy to change it be more similar to the rest of the metrics module, accepting the output of filters as an input but i prefer the one stop shop...also not married to the name obviously

**Comment by jgostick** [comment]
* What does it return?  
* Maybe the ``metrics`` functions should accept an optional argument, like ``bin_im`` or ``imb`` that will do the filter using default args.  Actually, we could even pass all kwargs onto the filter, so you could technically control how the filter is run.  

Also, can you push this and turn it into a PR?
