### ISSUE TITLE
skimage regionprops deprecation warning

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/porespy#100]
http://scikit-image.org/docs/0.14.x/release_notes_and_installation.html#deprecations

2d regionprops is switching from xy to rc (row-column) coordinates. 

It will remain backwards compatible using parameter coordinates='xy' but this will be removed in 0.16.

We should test our functions with the new mode

**Comment by jgostick** [comment]
in PR #145 I have used the coordinates='xy' keyword to avoid this warning
