### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#122]
When running snow_basic example, I get a few deprecation warnings.
```
Partitioning Pore Space using Marker Based Watershed
/home/amin/anaconda3/envs/pmeal/lib/python3.6/site-packages/porespy/network_extraction/__snow__.py:210: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  peaks_i = labels[s] == i+1
```
It seems like there's an easy fix by using `tuple(seq)` instead of `seq` for indexing. I don't really know what's going on in `snow` and so I don't want to make any changes that breaks it. Maybe @Zohaib-Atiq  would like to double check and make the necessary changes?

**Comment by jgostick** [comment]
This seems to be gone in the latest dev branch, so closing
