### ISSUE TITLE
bug in snow_partitioning( ) in the master branch

### ISSUE THREAD

**Issue by bo-guo** [PMEAL/porespy#124]
Line 97: 
regions = watershed(image=-dt, markers=peaks, mask=dt > 0)

If the Gaussian blur filter is applied, the distance map dt has already been modified. Using dt as a mask leads to an image differing from the original image.

**Comment by jgostick** [comment]
@Zohaib-Atiq Can you look into fixing this bug asap?  Make sure that all our pre-packaged snow functions do not use the gaussian blurred DT for anthing other than finding peaks.

**Comment by Zohaib-Atiq** [comment]
#125 fixed in `dev`.
