### ISSUE TITLE
Add Tests...lots of tests!

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#13]
I added Codecov last night and less than 50% of the code is tested....we can surely get this to 100% given the narrow focus of the code base.  

Here is how to add a test:
* There are files in the `test/unit` folder for each module.  To add a test you just add a new function to the file that follows the same naming convention as the existing tests.  
*All function names start with `test` followed by the functionality being tested, like `apply_chords`, and ending with some indication of the test scope, like `spacing`, so `test_apply_chords_with_spacing`.  
* It is good practice to write small tests that only test one thing, so when it fails you know exactly why.
* Tests should be fast so just use small images.  Perhaps the image could be 2D if possible.
* A typical test will run some function or filter on an image, then check that the output has the expected properties.  This means the image should be the same each time the test is run.  This can accomplished by setting Scipy's random number generator state to a known value before generating an image (like `blobs`).  
* If you're going to use an image in multiple tests, then you can create it in the ``setup_class`` function, which gets called before all test functions, and append the image to the object (e.g. ``self.im = test_image``).  This save generating it each time.

**Comment by TomTranter** [comment]
I've had a good go at this and scooped up all the low hanging fruit. :)

**Comment by RodericDay** [comment]
The slowest test by far is RandomWalk's doctest. Do you intend for the doctests to be run alongside the unit test suite by default?

**Comment by TomTranter** [comment]
Yes that would be the intention but you're right it is a bit slow and probably covers the same code as the unit tests but serves as a reminder of how to use the function.

**Comment by jgostick** [comment]
yes, we're running doc tests, mostly to make sure the examples in teh docs
aren't broken
