### ISSUE TITLE
Remove simulation submodule

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#140]
I would like to remove the ``simulations`` module.  This module contains a wrapper for PyTrax and a wrapper for Porosimetry.  Neither of these really needed anymore.  

We've moved porosimetry to a set of filter/metrics functions, so it's totally useless.  

As for pytrax, I propose adding a new metric called ``tau_tensor`` that runs pytrax and returns tau values for all three directions.  The docstring could point people to the actually pytrax package for those that want more control / info.

**Comment by sreeyuth** [comment]
I fully agree.  porespy is purely for pore space analytics, so deleting the simulations module brings a lot of clarity. We have openpnm for 'simulations' anyway.

**Comment by jgostick** [comment]
done in PR #145
