### ISSUE TITLE
to_vtk throws an error when given 2D image

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#149]
Just wanted to make sure if this was intended behaviour (@jgostick ), otherwise I can push a quick fix.

**Comment by jgostick** [comment]
Not intended as far as I know

**Comment by jgostick** [comment]
@mdrkok Can you also look into this while you're investigating the other vtk issue?

**Comment by mdrkok** [comment]
Will do

**Comment by TomTranter** [comment]
addressed in PR #156
