### ISSUE TITLE
Error running notebook examples/networks/snow_advanced.ipynb

### ISSUE THREAD

**Issue by yxqd** [PMEAL/porespy#152]
The last cell
```
im = ps.tools.align_image_with_openpnm(im).astype(int)
ps.io.to_vtk(im, path='.extracted_network')
```
throws an exception:

```
NameError                                 Traceback (most recent call last)
<ipython-input-10-92dfcb2e4b35> in <module>
      1 im = ps.tools.align_image_with_openpnm(im).astype(int)
----> 2 ps.io.to_vtk(im, path='.extracted_network')

~/miniconda2/envs/test-porespy/lib/python3.7/site-packages/porespy/io/__funcs__.py in to_vtk(im, path, divide, downsample, voxel_size, vox)
    120                    spacing=(2*vs, 2*vs, 2*vs))
    121     else:
--> 122         imageToVTK(path, cellData={'im': np.ascontiguousarray(im)},
    123                    spacing=(vs, vs, vs))
    124 

NameError: name 'imageToVTK' is not defined
```

**Comment by jgostick** [comment]
@mdrkok Can you look into this one?  This is the vtk io function that you cooked up.

**Comment by TomTranter** [comment]
Not sure if @mdrkok received this notification. It must be a requirements issue. imageToVTK comes from the pyevtk package which may not have been installed. 

This probably stemmed from the fact that pyevtk was not up to date on pip and we use to get it from a bitbucket account. 

https://github.com/PMEAL/porespy/blob/master/porespy/io/__funcs__.py

Has the following lines which I guess don't show up in the notebook

try:
    from pyevtk.hl import imageToVTK
except:
    print("warning: pyevtk must be install manually")

The pip version of pyevvtk is now up to date though so we can include it as normal.

Just out of interest which branch of porespy and porespy examples are we working from for this review? I noticed our master branch in the examples is quite different now to the notebooks branch and this example is not even in the notebooks and the one in master is using OpenPNM v.1 style ...

I can help clean up the notebooks tomorrow

**Comment by mdrkok** [comment]
I did receive the notifications, the issue is almost certain what tom said, we just started getting pyevtk through pip so its probably just an import error

**Comment by yxqd** [comment]
I was running the notebooks in this repo. Only later I realized there is another repo dedicated for notebook examples. It would be better to consolidate them so that it is less confusing. Thanks!

**Comment by jgostick** [comment]
We fixed the pyEVTK error, and have also moved all examples from the examples repo to the example folder of the main repo.  I will update the examples repo accordingly.
