### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by yxqd** [PMEAL/porespy#153]
Refs openjournals/joss-reviews#1296

It is great that tests for many algorithms are included. Some tests could be improved to boost user confidence on the algorithms. For example it looks to me that this test https://github.com/PMEAL/porespy/blob/8045f506364e6278c68cf5ebaaff4ef604bc13a1/test/unit/test_filters.py#L170 only checks the maximum of the result. Could you please add some simple tests that contain more validation? For this particular example, maybe you can add a test that

* uses a fixed input image instead of a random image
* compares the result of the filter to a saved, expected result, and makes sure the difference is within a tolerance.

**Comment by jgostick** [comment]
Our approach is to create an identical image at the initialization of the test class (self.im), then use it for all tests.  This saves us having to store a 200**3 image in the repo.  We ensure the image is identical each time to setting the seed of the random number generator then calling ``blobs``.  

To make sure this approach is solid I have added an assert statement that checks the porosity.

There were also several recently added tests that did not use ``self.im`` so I changed those.
