### ISSUE TITLE
improve documentation: references or brief descriptions of some algorithms

### ISSUE THREAD

**Issue by yxqd** [PMEAL/porespy#154]
Refs openjournals/joss-reviews#1296

Could you please consider adding brief descriptions or references for implementations for algorithms. For example the local thickness algorithm:https://github.com/PMEAL/porespy/blob/8045f506364e6278c68cf5ebaaff4ef604bc13a1/porespy/filters/__funcs__.py#L833 
The description on what it does is clear, but the implementation is not explained or referenced. A good example is the documentation for the reconstruction algorithms in tomopy: https://tomopy.readthedocs.io/en/latest/api/tomopy.recon.algorithm.html

**Comment by jgostick** [comment]
Many functions already had documentation.  The functions that do not are our own implementations.  For instance, our local thickness does not work the same as the imageJ version.  Nonetheless, I have added references in several places as best I can.

**Comment by yxqd** [comment]
I think your implementation of local thickness algorithm is quite ingenious. It is fast and simple, although it has a clear limit of accuracy determined by parameter `sizes`. I have to read your documentation and code carefully to understand it. So it would be very helpful for users that some words are added about your own implemenations, like this one, explaining it is different from ImageJ, its performance, its limitation, etc.

**Comment by jgostick** [comment]
Ingenious is a bit of a stretch, but I'm glad you approve!  I just realized as some point that it was 'porosimetry' without access limitations.  I think it's probably too much to explain in the doc string, and we're trying to keep the "docs" lean so we don't have to maintain too much.  I think a better approach would be an example in the examples repo which I'm touching up right now.  I can link to it from the docstring.  In fact, that is a a GREAT idea for ALL the functions, to link to a proper notebook with plenty of explanation.
