### ISSUE TITLE
noise function

### ISSUE THREAD

**Issue by cr458** [PMEAL/porespy#160]
The [`noise`](https://github.com/PMEAL/porespy/blob/8045f506364e6278c68cf5ebaaff4ef604bc13a1/porespy/generators/__imgen__.py#L480) function seems to require the installation of a package. 

1. Could we change the name of this function to `generate_noise`, or `get_noise` since it has the same name as the `noise` package.

2. Can we include the `noise` package in `requirements.txt`?

**Comment by jgostick** [comment]
Name has been changed, but I don't want to add the package to our requirements since it cannot be installed from pip on windows machines as it needs to be compiled.  I can be installed from conda, so that information is included in the docstring.
