### ISSUE TITLE
snow and snow_dual files

### ISSUE THREAD

**Issue by cr458** [PMEAL/porespy#163]
More of a suggestion than a rigid issue: would it make sense to combine `snow` and `snow_dual` into the same .py file, and create a separate `Network_Dict` class/namedtuple that both functions had access to and could be returned without defining the class within both functions separately?

**Comment by jgostick** [comment]
We've actually done part of this in a branch that was merged to dev last week.  The Network_Dict class is now in a utils file, and is used by snow, snow_dual, and snow_n.  We also refactored these three algorithms to all call the same set of functions.  Regarding combining into same file, I prefer separate files to help keep file length manageable.
