### ISSUE TITLE
snow_partitioning_n returns regions labelled zero when all space in image belongs to a phase

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/porespy#169]
Trying to do a 3-phase segmentation and all space in image belongs to a phase i.e. no solid anywhere. Running snow_n produced erroneous throat connections and I traced this back to snow_partitioning_n returning some regions labelled zero. I'll try and debug further but could be something in watershed settings

**Comment by Zohaib-Atiq** [comment]
Never faced this issue before. If possible can you send me the exact image which you are sending in snow_n?

**Comment by TomTranter** [comment]
I've managed to reproduce it with a generated image. The first two commented out images work and the polydisperse spheres don't. The problem seems worse for smaller features but it's not limited to them, I think the root cause lies in removing peaks that are identified wrongly as saddle points. 
```python
import porespy as ps
import openpnm as op
from skimage import io
from scipy.stats import itemfreq
import scipy.ndimage as spim
import numpy as np
import scipy as sp
from porespy.filters import snow_partitioning

np.random.seed(1)

#im = ps.generators.lattice_spheres(shape=[100, 100, 100], radius=5, offset=5).astype(np.uint16)
#im = ps.generators.blobs(shape=[50, 100, 200], porosity=0.2, blobiness=0.3).astype(np.uint16)
im = ps.generators.polydisperse_spheres([50, 100, 200], porosity = 0.5,
                                        dist=sp.stats.norm(loc=20, scale=10)).astype(np.uint16)
lab, N = spim.label(im == 0)
print(itemfreq(lab))
for i in np.arange(1, N, 2):
    im[lab == i] += 2
im += 1

print(itemfreq(im))
net = ps.networks.snow_n(im, voxel_size=1)
pn = op.network.GenericNetwork()
pn.update(net)
#lab_2d = np.sum(lab, axis=2)
#fig = plt.figure()
#plt.imshow(lab_2d)
for i in range(net.regions.max()):
    lab, N = spim.label(net.regions == i)
    if N > 1:
        print(i, N)
        
im_aligned = ps.tools.align_image_with_openpnm(im)
trim_regions = net.regions[3:-3, 3:-3, 3:-3]
regions_aligned = ps.tools.align_image_with_openpnm(trim_regions)
io.imsave('zohaib_im_aligned.tif', im_aligned)
io.imsave('zohaib_regions_aligned.tif', regions_aligned)

op.io.XDMF.save(network=pn, filename='zohaib_net')

#######################################################################
# Code from snow_partitioning_n
#######################################################################
r_max=4
sigma=0.4
return_all=True
mask=True
randomize=False
alias=None

# Perform snow on each phase and merge all segmentation and dt together
phases_num = sp.unique(im * 1)
phases_num = sp.trim_zeros(phases_num)
combined_dt = 0
combined_region = 0
num = [0]
for i in phases_num:
    print('_' * 60)
    phase_snow = snow_partitioning(im == i,
                                   dt=None, r_max=r_max, sigma=sigma,
                                   return_all=return_all, mask=mask,
                                   randomize=randomize)
    if len(phases_num) == 1 and phases_num == 1:
        combined_dt = phase_snow.dt
        combined_region = phase_snow.regions
    else:
        combined_dt += phase_snow.dt
        phase_snow.regions *= phase_snow.im
        print('*'*50)
        print('Zero labelled regions', np.any((phase_snow.regions==0)*phase_snow.im))
        print('*'*50)
        phase_snow.regions += num[i - 1]
        phase_ws = phase_snow.regions * phase_snow.im
        phase_ws[phase_ws == num[i - 1]] = 0
        combined_region += phase_ws
    num.append(sp.amax(combined_region))
```

**Comment by TomTranter** [comment]
It's also hidden a little as the zeros in the second and third phases have their indices increased by num[i-1] so there are multiple non-zero regions too which you can find when you count the labelled images. This problem could be solved by inserting an extra labelling step as it seems to happen for isolated regions mostly and we could just give them a region number after the watershed but that is messy and it would be better if the peaks were not removed in the first place

**Comment by TomTranter** [comment]
Any luck figuring this out @Zohaib-Atiq ?

**Comment by Zohaib-Atiq** [comment]
@TomTranter this is coming from snow_partitioning function. Changing r_max and sigma value changes the total number of peaks before watershed step. How much percentage of material you are losing in your image. If it is less then 1% then I think it should not change the results that much?

**Comment by TomTranter** [comment]
It's not just losing material that is the problem. It creates multiple separate regions with same label and this results in erroneous throat connections. I'll look into it more

**Comment by Zohaib-Atiq** [comment]
These extra material is labeled zero in combined watershed which is neglected while extracting network. In your case what label you are getting for these multiple regions? It should be zero.

**Comment by TomTranter** [comment]
Run the script and look at the counts

**Comment by Zohaib-Atiq** [comment]
These regions are labeled zero in the script you posted. Which is neglected in the network extraction stage.

**Comment by Zohaib-Atiq** [comment]
The script shows all such regions labeled zero. It makes 0.55% of the whole image. Total count is 5543 out of 1000000 voxels.

**Comment by TomTranter** [comment]
I think it happens when the regions are isolated. I have a script here that reproduces the problem with 20% of the space labelled zero

```python
import numpy as np
from scipy import ndimage as spim
from skimage import io
import porespy as ps
import openpnm as op

im = np.ones([24, 22, 21])
im[8, 10, 0] = 0
im[10, 10, -1] = 0
im[0, 11, 10] = 0
im[-1, 10, 10] = 0
im[9, 0, 10] = 0
im[10, -1, 10] = 0
dt = spim.distance_transform_edt(input=im)
dt[dt < 3] = -1
dt[(dt > 0)*(dt < 6)] = -2
dt[dt > 0] = -3
dt *= -1
dt = dt.astype(np.uint16)
im = np.tile(dt, [2,2,2])
io.imsave('isolated_space.tif', im.astype(np.uint16))
snow = ps.networks.snow_n(im)
trim_regions = snow.regions[3:-3, 3:-3, 3:-3]
io.imsave('isolated_regions.tif', trim_regions.astype(np.uint16))

net = op.network.GenericNetwork()
net.update(snow)
net.num_pores()
for i in range(3):
    print(i, net.num_pores('phase'+str(i+1)))
    
print('% Zero Space', 100*np.sum(trim_regions == 0)/np.size(trim_regions))
```

**Comment by TomTranter** [comment]
@jgostick, @Zohaib-Atiq I also have a branch that fixes the problem but it breaks other tests. See the PR.

**Comment by jgostick** [comment]
I just came across this issue myself.  i have done a drastic overhaul of the snow funcs and this is now caught at the multiphase extraction level.  it still happens in the watershed function though.  i have added a comment to the code and will open up a more concise issue.
