### ISSUE TITLE
Error in fibrous media generation

### ISSUE THREAD

**Issue by angelswat** [PMEAL/porespy#171]
Hi (@jgostick @TomTranter )

I have a problem in fibrous media generation because I have obtained a fibrous media not similar to how is a real fibrous media.

![fibers](https://user-images.githubusercontent.com/32890792/58108689-e56c0400-7bb1-11e9-8e4f-0806cf9a6d6d.png)

You have put in your jupyter notebok an incredible fibrous media. Please help me, how can I fix this error?

**Comment by TomTranter** [comment]
can you post the code please

**Comment by angelswat** [comment]
import porespy as ps
import matplotlib.pyplot as plt
import imageio
import scipy as sp
import scipy.ndimage as spim
import openpnm as op
from porespy.filters import find_peaks, trim_saddle_points, trim_nearby_peaks
from skimage.morphology import watershed
from porespy.tools import randomize_colors

im = ps.generators.cylinders(shape=[300, 300, 300], radius=5, ncylinders=200)
plt.imshow(ps.visualization.sem(im), cmap=plt.cm.bone)
plt.axis('off')
plt.show()

This is the same code you can find in your jupyter notebook, but I cant get your fibrous media.

**Comment by jgostick** [comment]
Your image is great, you just need to view it from a different angle.  

Specify the direction as Y or Z, such as:

```
plt.imshow(ps.visualization.sem(im, direction='Y'), cmap=plt.cm.bone)
```

**Comment by angelswat** [comment]
Perfect!
Thank you so much!
