### ISSUE TITLE
porespy.filters.porosimetry

### ISSUE THREAD

**Issue by fjkr5** [PMEAL/porespy#185]
Hello all,

I am writing for asking a question about the code: porespy.filters.porosimetry(im, sizes=25, inlets=None, access_limited=True, mode='hybrid')

If I want to modify the inlets, what should I do? For example, I need the inlets on y and z direction to be zero and only keeps the values on x direction. Can you please tell me what to do? Or any examples about modify inlets. Thank you!

**Comment by jgostick** [comment]
You make an image the same size as your ``im`` with all zeros, so:

```
in = sp.zeros_like(im, dtype=bool)
```

Then you put 1's on the borders where you want invasion to occur from, like:

```
in[0, :, :] = True
in[-1, :, :] = True
```

This will all invasion from both x=0 and x=X faces.  

Note that there seems to be a bug in the current implementation of our ``trim_disconnected_clusters`` function, which is called by the ``porosimetry`` function when you specify inlets.  We have pushed a fix to the *dev* branch, but it's not part of the pip package yet.  

If the above code doesn't seem to work right for you, then come back here an leave a comment, and I"ll help you get the dev branch working if you don't already know how.

**Comment by fjkr5** [comment]
Hi Dr. jgostick

Thanks for your responding! I tried your code but it returns that:

'    in = sp.zeros_like(im, dtype=bool)
     ^
SyntaxError: invalid syntax'

So I used 'imm' instead of 'in' as 'imm = sp.zeros_like(im, dtype=bool)'

I didn't see the trim_disconnected_clusters function, but only trim_disconnected_blobs function from Porespy Docs. Can you please specify how it works? How can I combine im and imm together? Thanks a lot!

**Comment by jgostick** [comment]
You can see the docstring for the ``trim_disconnected_blobs`` function if you're using an IDE that renders help function.  Spyder does this.  You can also see it on the web version of the documentation [here](https://porespy.readthedocs.io/en/master/modules/filters.html#porespy.filters.trim_disconnected_blobs)

**Comment by jgostick** [comment]
``in`` is a protected python keyword, so maybe that was the problem.

**Comment by fjkr5** [comment]
Hi Dr. jgostick，

Thanks for your information. But I didn't figure out what's the problem on 'in'. I am trying to use 'mip.set_inlets'. Do you think this is acceptable? If I want this drainage occurs in x direction, how can I know this is 'lefft', 'right' ,'front' or 'back'? Thank you!

**Comment by jgostick** [comment]
``mip.set_inlets`` is a method on the Porosimetry class in OpenPNM.  I thought your question was about PoreSpy (this repo).  Am I missing something?

**Comment by fjkr5** [comment]
My question is about PoreSpy, I am wondering if I can try OpenPNM to solve
this problem. Thank you!

**Comment by jgostick** [comment]
```
import porespy as ps
import scipy as sp
import matplotlib.pyplot as plt
im = ps.generators.blobs(shape=[500, 500], porosity=0.8)
bndry = sp.zeros_like(im)
bndry[:, 0] = True
mip = ps.filters.porosimetry(im=im, inlets=bndry)
plt.subplot(1, 2, 1)
plt.imshow(mip)
psd = ps.metrics.pore_size_distribution(mip, log=False)
plt.subplot(1, 2, 2)
plt.plot(psd.R, psd.cdf)
```

**Comment by fjkr5** [comment]
Hi Dr. jgostick，

It works. Thank you sooo much!!

**Comment by fjkr5** [comment]
Hi Dr. jgostick，

I run this in 3D and my code is shown as following:

import porespy as ps
import matplotlib.pyplot as plt
import scipy as sp

im = ps.generators.bundle_of_tubes(shape=[40, 40, 40], spacing=0.01)
bdy = sp.zeros_like(im)
bdy[0, :, :] = 1 
bdry = bdy*im

mip = ps.filters.porosimetry(im=im,inlets=bdry)
print(mip)

result = ps.metrics.pore_size_distribution(mip, log=False)
print(result.R, result.cdf)

plt.subplot(1, 2, 1)
plt.imshow(mip)
psd = ps.metrics.pore_size_distribution(mip, log=False)
plt.subplot(1, 2, 2)
plt.plot(result.R, result.cdf)

I think 'im = ps.generators.bundle_of_tubes(shape=[400, 400, 400], spacing=0.01)' maybe incorrect. I also tried 'im=openpnm.network.Cubic(shape=[400, 400, 400], spacing=0.01)', but it doesn't work either. Can you please take a look of it? Thank you!

**Comment by jgostick** [comment]
You didn't tell me what error message you're getting, so I don't know where you're having trouble.

From your above code I see a few problems though:
1.  You can't use ``plt.imshow`` with a 3D image,  you can only look at slices, like ``plt.imshow(mip[:, :, 50])``
2. You are mixing up porespy and openpnm again.  PoreSpy is all about images, while OpenPNM is all about networks.  So the line ``im=openpnm.network.Cubic(shape=[400, 400, 400], spacing=0.01)`` is not valid.  OpenPNM does NOT return an image.

**Comment by fjkr5** [comment]
Thanks for your responding. My code is:
'
import porespy as ps
import matplotlib.pyplot as plt
import scipy as sp

im = ps.generators.bundle_of_tubes(shape=[400, 400, 400], spacing=0.01)
bdy = sp.zeros_like(im)
bdy[0, :, :] = 1
bdry = bdy*im

mip = ps.filters.porosimetry(im=im,inlets=bdry)
print(mip)

result = ps.metrics.pore_size_distribution(mip, log=False)
print(result.R, result.cdf)

plt.subplot(1, 2, 1)
plt.imshow(mip[200,:,:])
psd = ps.metrics.pore_size_distribution(mip, log=False)
plt.subplot(1, 2, 2)
plt.plot(result.R, result.cdf)'

And the error is:

   'im = ps.generators.bundle_of_tubes(shape=[400, 400, 400], spacing=0.01)
  File
"/home/testing/anaconda3/lib/python3.7/site-packages/porespy/generators/__imgen__.py",
line 233, in bundle_of_tubes
    r = sp.random.randint(1, (spacing/2))
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken'

Thank you!

**Comment by jgostick** [comment]
try putting spacing as an integer, like 20.  In porespy all spacing and shape values are taken as integers meaning number of voxels in each direction.  It is up to the use to keep track of the um/voxel resolution of their images when working with the images.

**Comment by fjkr5** [comment]
Hi Dr. jgostick，

I changed the spacing to 10 and my code is:

'import porespy as ps
import matplotlib.pyplot as plt
import scipy as sp

im = ps.generators.bundle_of_tubes(shape=[400, 400, 400], spacing=10)
#bdy = sp.zeros_like(im)
#bdy[0, :, :] = 1
#bdry = bdy*im

mip = ps.filters.porosimetry(im=im)
print(mip)

result = ps.metrics.pore_size_distribution(mip, log=False)
print(result.R, result.cdf)

plt.subplot(1, 2, 1)
plt.imshow(mip[200,:,:])
psd = ps.metrics.pore_size_distribution(mip, log=False)
plt.subplot(1, 2, 2)
plt.plot(result.R, result.cdf)
plt.show()'

My problem is comparing the result of pore size distribution with inlets
and no inlets, the difference is really small, it only appears 2 or 3
digits after the decimal point.

Do you know the potential reason or do you have any suggestions on it?
Thank you!

**Comment by jgostick** [comment]
With the bundle of tubes image there should be NO difference between specifying inlets or not. Why are you doing this on a bundle of tubes image?  That image generator was only added for some visualizations, but is not really meant for meaningful simulations.

**Comment by fjkr5** [comment]
Hi Dr. jgostick，

Thanks for your explanation. I would like to generate a pore size
distribution for a real 3D image and set inlets to simulate drainage in
different directions. But I found that the results are very similar no
matter I set the inlets or not. My code is listed as following. The only
difference is SimpleITK part. Thank you!

'import SimpleITK as sitk
import porespy as ps
import matplotlib.pyplot as plt
import scipy as sp

data = sitk.ReadImage('image.mhd') # rename
im = sitk.GetArrayFromImage(data)
bdy = sp.zeros_like(im)
bdy[0, :, :] = 1
bdry = bdy*im

mip = ps.filters.porosimetry(im=im,inlets=bdry)
print(mip)
result = ps.metrics.pore_size_distribution(mip, log=False)
print(result.R, result.cdf)

fig1=plt.figure()
plt.imshow(mip[200,:,:])
fig2=plt.figure()
plt.plot(result.cdf, result.R, 'rx-')
plt.show()'

**Comment by jgostick** [comment]
OK, I think you are experiencing the bug in our ``trim_disconnected_blobs`` function, which ``porosimetry`` uses internally when you pass in ``inlets``.  I will organize a bug-fix release of PoreSpy soon.  In the mean time, you can use the dev branch.  Do you know how to do this?

**Comment by fjkr5** [comment]
Sorry I am not familiar with it. Can you please send me link of that?

**Comment by jgostick** [comment]
You need to:
1. install a git client, like sourcetree, fork, or gitkraken
2. clone our repo into the git client (using the link provided at the top of the github page).  This will make a local copy of our code on your machine.
3. in the git client 'check out' the dev branch, which will changes all the local files with the corresponding changes
4. open the conda prompt and change directory to the location where you told your git client to store porespy.
5. upgrade porespy in the conda prompt with ``pip install --upgrade -e .`` 
6. next time you start spyder or jupyter it will use this new installation.  

This is probably a lot of new info for you.  You could just wait a few weeks for us to update porespy.  

I do not have the time to help you with this any longer.  Could you please try to find a colleague around you that is familiar with python and git.  They should be able get this going for you easily without knowing anything about porespy.

**Comment by fjkr5** [comment]
OK. Thanks so much for your help!

**Comment by jgostick** [comment]
I decided it was a good time to merge the latest dev version into master and push the whole thing to PyPI.  You should be able to get the latest version now, including the bugfix in ``trim_disconnected_blobs`` which is affecting the ``porosimetry`` function, using:

``pip install --upgrade porespy``

**Comment by fjkr5** [comment]
It would really help me a lot. Thank you so much for your information.
