### ISSUE TITLE
[Question] Voxel Scaling

### ISSUE THREAD

**Issue by abrafcukincadabra** [PMEAL/porespy#186]
In the Docstring for pore_size_distribution, it states:
```(1) To ensure the returned values represent actual sizes be sure to scale the distance transform by the voxel size first (``dt *= voxel_size``)```
I have a couple of questions regarding voxel scaling.

1. Is it necessary to scale both the distance transform (dt) array in Local Thickness (lt) filter and Pore Size Distribution (psd) metric? From my understanding, voxel size should be kept ```= 1``` in the psd function and only be applied to the dt array in lt filter since psd will read the results which are already scaled. Is this correct?
2. I apologise if this question sounds stupid, but what should the ratio of scaling be? Is it pixels/unit or units/pixel?

**Comment by jgostick** [comment]
This seems like it might be a mis-wording in the docsring.  Both local thickness and porosimetry function require the distance transform to be in voxel units, not actual units.  If you want to the ``pore_size_distribution`` function to return actual units, then you must scale the result of the local thickness filter and/or the porosimetry filter before sending to ``pore_size_distribution``.  You best bet is to do everything in voxel units, the just scale yourself after you get a result...the there is no confusion.

**Comment by abrafcukincadabra** [comment]
Right, so just to be clear, if I wanted the final results to be in millimeters, then I should either apply scaling to the imresults array from porosimetry filter before sending the results to the psd metric or apply scaling only in psd metric using the voxel_size parameter? Or, I can manually alter the radius values in the psd metric output tuple myself using a completely different function, is that correct?

**Comment by jgostick** [comment]
Yes, scale the images from ``porosimetry`` and/or ``local_thickness``, so:

```
import porespy as ps
import matplotlib.pyplot as plt

im = ps.generators.blobs(shape=[300, 300])
mip = ps.filters.porosimetry(im)
lt = ps.filters.local_thickness(im)

vox_res = 0.001  # mm/voxel
psd = ps.metrics.pore_size_distribution(im=mip*vox_res, log=False)
# Plot using a simple lien plot
plt.plot(psd.R, psd.pdf)

psd = ps.metrics.pore_size_distribution(im=lt*vox_res, log=False)
# Make a nicer bar graph
plt.bar(x=psd.bin_centers, height=psd.pdf, width=psd.bin_widths, 
        edgecolor='k', linewidth=2)
```

**Comment by abrafcukincadabra** [comment]
Sorry I couldn't respond earlier. Thanks so much for your help!
