### ISSUE TITLE
enhance trim_nearby_peaks to accept a tolerance or threshold

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#193]
At the moment it trims peaks that are closer to another peak than to solid, but it'd be nice if we could put some sort of absolute AND relative tolerance, so it only trims peaks if they are too close to a nearby peak within some acceptable amount.

**Comment by Ni2M** [comment]
It is a good idea. I think we can apply this idea on https://github.com/PMEAL/porespy/blob/dd5c2240a3a7d0da5a03f2338ae54b5b885e373a/porespy/filters/__funcs__.py#L626.
