### ISSUE TITLE
Percolating Cluster Function

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/porespy#20]
Useful to have. I'm happy to add it. Where should it go, filters or metrics?

**Comment by jgostick** [comment]
Depends what it returns...an image of the percolating cluster (then a filter) and some stats about it (the a metric).  In fact, we typically add a filter, then a metric that accepts the filtered image an input. 

Not sure what the intention of this is.  There is already a find_disconnected_voxel, fill_blind_pores, and trim_floating_solid, which will basically do this.  Also, if you go ahead, there is a function in scikit-image that trims all voxels not connected to the borders of the image.  This is used in the find_disconnected_voxels function, so check it out.

**Comment by jgostick** [comment]
`find_percolating_voxels(im, faces=['x_lo', 'x_hi', 'y_lo'])`

**Comment by jgostick** [comment]
zohaib took care of this
