### ISSUE TITLE
noise.snoise3 doesn't take a seed argument

### ISSUE THREAD

**Issue by magnaou** [PMEAL/porespy#200]
This makes using "ps.generators.generate_noise(args)" reproducible and doesn't allow us to generate different media of the same size.

**Comment by jgostick** [comment]
The problem is that noise is an external package.  I don't know if it even uses the numpy random number generator.

**Comment by jgostick** [comment]
Also see issue #81

**Comment by jgostick** [comment]
This is now fixed with PR #223, since you can set the numpy random number generator before calling the function.
