### ISSUE TITLE
Direction for two-point correlation functions

### ISSUE THREAD

**Issue by ankitaeclipse** [PMEAL/porespy#205]
Hi,

Thank you for creating this library. 

I am trying to use two-point correlation functions on 3D binary porous media images. I was wondering if there was a way to extract the correlation lengths for x-, y-, z- directions?

Thank you.

**Comment by jgostick** [comment]
Not at the moment.  The 2 point correlation function works in all directions at once.  The chord length distribution might work for you though.  It is described in Torquato's textbook along side the 2 point correlation function so has a lot of the same qualities.  We have an example here:

https://github.com/PMEAL/porespy/blob/master/examples/filters/adding_chords.ipynb

**Comment by ankitaeclipse** [comment]
Thank you, Prof. Jeff for the help.

**Comment by jgostick** [comment]
Sometimes the notebook examples don't render on github.  If that happens just keep trying until it shows up. I will close the issue now, ok?
