### ISSUE TITLE
filters.fill_blind_pores function in 3D image

### ISSUE THREAD

**Issue by fabricix** [PMEAL/porespy#206]
It is not very clear for my how the function [filters.fill_blind_pores](filters.fill_blind_pores) works in 3D images.
The behavior of the function is clear with 2D images:
![Screenshot from 2019-11-08 10-58-12](https://user-images.githubusercontent.com/22794916/68482197-c45aa680-0217-11ea-880d-b200525ee927.png)
but in 3D images, I can not see the the filling of the blind pores, even in to an image where there is clearly a blind pore:
![image](https://user-images.githubusercontent.com/22794916/68483067-98402500-0219-11ea-8454-c8759f75299a.png)
Please, can you point to me some example where the filling of the blind pores is done in a 3D image?

**Comment by jgostick** [comment]
Hi @fabricix.  In your 3d image it (a) less likely that a pore is blind and (b) you possibly just chose a slice with no blind pores.  Have you check the im.sum() before and after?  It should be slightly less afterwards indicated that pores have been changed from 1 to 0.

**Comment by fabricix** [comment]
Hi @jgostick, the sums are the same `im.sum()=11830657, ps.filters.fill_blind_pores(im).sum()=11830657` (suggesting me there are not blind pores). In the follow image, you can see that the pore in the slice 88 appears after applying the filter, but slices 87 and 89 prove that the pore is blind. What it is wrong? Do you have an example showing this filter in a 3D image? thanks!  
![image](https://user-images.githubusercontent.com/22794916/68489373-bca1fe80-0225-11ea-84b8-2475c11e0053.png)

**Comment by jgostick** [comment]
It's possible there is a bug in the filter.  Which version of porespy are you using?

**Comment by jgostick** [comment]
Also, the green is the solid (I think), ``fill_blind_pores`` would remove yellow pixels.  There is also a function called ``trim_floating_solid`` which should remove the green.  Both call ``trim_disconnected_voxels``.  It's odd that the sums are the same though, so I still suspect you are using a version with a bug.

**Comment by fabricix** [comment]
> It's possible there is a bug in the filter. Which version of porespy are you using?

Name: porespy, Version: 1.2.0.

**Comment by jgostick** [comment]
I know there was a bug in this filter a while ago, but looking at master and dev, it seems that they are the same, so the bugfix was merged into master.  

Can you try inverting your image and seeing if the dots on slice 88 disappears? Or, try ``trim_floating_solid``.  I'll start making a notebook example as well, to debug, but also to add to the examples folder.

**Comment by fabricix** [comment]
> ould remove ye

yes, green and yellow are solid, purple is the pore space. My objective really is to expand the green phase progressively and to perform a parametric analysis. I need to keep all the other phases during the analysis so may be the `fill_blind_pores` is not needed, but during a test a found this behavior.
What filter can a use for expand in 3D a specific phase (green, yellow or purple)? `binary_dilation`?

**Comment by fabricix** [comment]
> I know there was a bug in this filter a while ago, but looking at master and dev, it seems that they are the same, so the bugfix was merged into master.
> 
> Can you try inverting your image and seeing if the dots on slice 88 disappears? Or, try `trim_floating_solid`. I'll start making a notebook example as well, to debug, but also to add to the examples folder.

There is not difference for my when applying the `trim_floating_solid`
![image](https://user-images.githubusercontent.com/22794916/68493423-3688b680-022b-11ea-9085-71f63b846eed.png)
, or when I invert the image
![image](https://user-images.githubusercontent.com/22794916/68493583-7d76ac00-022b-11ea-8b5d-adec1f07f96f.png)
the pore does not disappear.

**Comment by jgostick** [comment]
Ok, so most of the filters in porespy (and scipy.ndimage and skimage) are meant for binary images.  In porespy we assume 1 for void and 0 for solid.  It sounds like your image has 3 colors, but to use most filters you'll need to binarize the image to make your phase of interest be 1 and all other phases have 0. To do this, make several copies of your image, one for each phase, so for instance if your solid is a matrix with some filler in it:

```
matrix = im == 0
filler = im == 1
void = im == 2
```

Then you can dilate the ``filler`` and remove it from your matrix with:

```
from skimage.morphology import ball
filler = spim.binary_dilation(filler, structure=ball(5))
matrix[filler] = 0
```

Or something to that effect.  Does that help?

**Comment by fabricix** [comment]
Yes, I think it is a very useful approach, as you can see bellow, I can identify the each phase 
![image](https://user-images.githubusercontent.com/22794916/68496043-317a3600-0230-11ea-96a4-996011c00afa.png)
but when I do the dilation I have the follow error message
```python 
import numpy as np
import porespy as ps
import scipy.ndimage as spim
from skimage.morphology import ball
import imageio

file = 'image.tif'
im = imageio.volread(uri=file)

matrix_1 = im == 1
matrix_2 = im == 2
pore_space= im == 0
matrix_1_dill = spim.binary_dilation(matrix_1, structure=disk(1))
...
Traceback (most recent call last):

  File "<ipython-input-78-53c1384ee308>", line 12, in <module>
  matrix_1_dill = spim.binary_dilation(matrix_1, structure=disk(1))
  File ".../anaconda3/lib/python3.7/site-packages/scipy/ndimage/morphology.py", line 510, in binary_dilation
    if not structure.shape[ii] & 1:
IndexError: tuple index out of range
```
Does you have any idea why?

**Comment by jgostick** [comment]
great, so you can proceed from here?  BTW, if you do 'fill_blind_pores on the bottom-right image I *think* that the dots should all disappear.

**Comment by fabricix** [comment]
> great, so you can proceed from here? BTW, if you do 'fill_blind_pores on the bottom-right image I _think_ that the dots should all disappear.

yes, I am going to proceed from here,it will be great if we have an example of `fill_blind_pores` over a 3d image, thanks!

**Comment by jgostick** [comment]
Yes, I created a new branch, and started a notebook example.  I'll push it soon.  I'm going to close this issue since you seem to have it sorted out.
