### ISSUE TITLE
Throat.area and Throat.perimeter calculation

### ISSUE THREAD

**Issue by Artshap** [PMEAL/porespy#208]
[example.zip](https://github.com/PMEAL/OpenPNM/files/3806912/example.zip)

Dear development team,

I am using porespy to create a pore network and export it to csv using openpnm. When I have exported it I noticed that values for throat area and perimeter are strange and although the source codes are straightforward, they do not match the manual calculation. I am not sure if I should use the provided values for calculating the shape factor or re-calculate area and perimeter myself.

I was under the assumption that porespy generated network throats are all cylinders for throats and spheres for pores. 

Could you please let me know what is the underlying calculation there or if I am wrong somewhere? 

Screenshot from excel is below.

![openpnm](https://user-images.githubusercontent.com/49969695/68171749-25d90600-ffc9-11e9-9224-54136cfed08a.png)

**Comment by kweishaupt** [comment]
@jgostick @Zohaib-Atiq  Sorry to stir this up again, but I am encountering throat perimeters of zero (while the other throat properities look ok), both with and without `marching_cubes_area`. Is there anything I can do about that?

This is related to the data discussed in https://github.com/PMEAL/porespy/issues/326

**Comment by jgostick** [comment]
Yes...delete them :-)  Some of the properties coming from boundary pores are not correct.  The new PoreSpy IO class in OpenPNM tries to fix them, but we need to the upstream problem in PoreSpy soon.

**Comment by kweishaupt** [comment]
Thanks :-)

Just as a note: not only throats a the boundary are affected, but also interior ones.

**Comment by kweishaupt** [comment]
@jgostick I think this issue occurs for internal throats with an cross-sectional area of just one pixel. Maybe one could assign `4*voxel_size` as an approximation.

**Comment by kweishaupt** [comment]
@jgostick Using the same dataset as described in my latest posts in  #326 ('snow' or 'snow_dual'), marching_cubes yields several pore throat areas of just one pixel for internal throats. Switching off marching_cubes yields more reasonable values:
![image](https://user-images.githubusercontent.com/74908731/105967068-bba4f900-6085-11eb-9451-c5178fc2ddb1.png)

area_mc = voxel_size*voxel_size =  (5.345e-6)^2

**Comment by jgostick** [comment]
Marching cubes does not like small regions.  It's one of reason we used a 3-voxel thick boundary.  I guess it would be better to make the marching cubes function check for the region size, and return the 'basic' answer for those cases.
