### ISSUE TITLE
What is the meaning of pore area anyway

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#218]
Pore area is poorly defined since it is directionally dependent and also varies with position in the pore.  This should be calculated using something like 'conduit_length' models in openpnm.  It IS used by the classic conductance models which assume the pore is actually a cylinder.

**Comment by ma-sadeghi** [comment]
For future reference: in the most recent refactoring of OpenPNM shape factors (to be called size factors), we removed the `pore_area` module altogether.
