### ISSUE TITLE
[Question] Visualize Output in Paraview

### ISSUE THREAD

**Issue by ZHHYKU** [PMEAL/porespy#222]
I am a beginner and I am confused about how to visualize the vtp file in the example snow_basic.ipynb.  It seems other steps should be taken after importing the vtp file. Although it is an easy question，I failed to get the results showed on the website. Could you give me more details on those steps or some helpful documents? Thank you.

**Comment by ma-sadeghi** [comment]
Hi @ZHHYKU I assume you figured it out yourself, or did you close this issue by mistake?

**Comment by ZHHYKU** [comment]
@ma-sadeghi Yeah, I find a video on the YouTube,  and I think that could be helpful for the example mentioned above. Thank for your reply.
