### ISSUE TITLE
Scipy 2 deprecation proofing

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#229]

**Comment by vasudevanv** [comment]
Does this mainly concern the deprecation of NumPy functions exposed via the root SciPy namespace? I have switched over some of the references in a local copy of porespy that I have been playing with.

**Comment by ma-sadeghi** [comment]
Yes. That'd be great if you could make a pull request @vasudevanv

**Comment by vasudevanv** [comment]
I can do that. Just one question, for some reason I have not been able to get pytest to discover the tests on my machine. How do you run your tests?
