### ISSUE TITLE
Integer overflow in _radial_profile in metrics\__funcs__.py

### ISSUE THREAD

**Issue by kleinerELM** [PMEAL/porespy#237]
I am just trying to use porespy and stumbled across an integer overflow error:

>   File "...\porespy\metrics\__funcs__.py

", line 332, in _radial_profile
>     radial_sum[i] = np.sum(autocorr[mask])/np.sum(mask)
> OverflowError: Python int too large to convert to C long

It seems this is easily fixable changing line 325 in .\porespy\metrics\__funcs__.py from 
`radial_sum = np.zeros_like(bins)`
to
`radial_sum = np.zeros_like(bins, np.int64)`

The error occured following [this example](https://porespy.readthedocs.io/en/master/getting_started.html#calculating-metrics) of the documentation using an real data image (8-bit TIFF, 1024x880):
```
im = cv2.imread( settings["referenceFilePath"], 0 )
data = ps.metrics.two_point_correlation_fft(im)
fig = plt.plot(*data, 'bo-')
plt.ylabel('probability')
plt.xlabel('correlation length [voxels]')
plt.show()
```

**Comment by ma-sadeghi** [comment]
Hi @kleinerELM, can you share your image by any chance so I can reproduce the bug?

**Comment by kleinerELM** [comment]
Sorry I forgot to attach it:

[C2-C3S 28d cryoBIB_004-cut.zip](https://github.com/PMEAL/porespy/files/4551299/C2-C3S.28d.cryoBIB_004-cut.zip)

**Comment by ma-sadeghi** [comment]
I was able to run your script, except that I read the image using `imageio` library via 
```python
import imageio
im = imageio.imread("C2-C3S 28d cryoBIB_004-cut.tif")
```
which I don't think should make a difference.

Can you post the exact error message you got? Also, what's your Python/porespy version?

**Comment by kleinerELM** [comment]
I was using porespy 1.2.0, freshly installed using 

> pip install porespy

Enviornment:
Win 10 Pro 1909
Python 3.7.2
numpy 1.15.4

Errormessage (stripped full folder paths):
```
Traceback (most recent call last):
  File ".\porespy_test.py", line 68, in <module>
    data = ps.metrics.two_point_correlation_fft(im)
  File ".\porespy\metrics\__funcs__.py", line 370, in two_point_correlation_fft
    tpcf = _radial_profile(autoc, r_max=np.min(hls))
  File ".\porespy\metrics\__funcs__.py", line 329, in _radial_profile
    radial_sum[i] = np.sum(autocorr[mask])/np.sum(mask)
OverflowError: Python int too large to convert to C long
```

And ideed, the value 9615212611.875 is assigned to the radial_sum[i] at one point. And since the radial_sum list only contains int32e (as the array bins, which dtype is used to initiate radial_sum), the value exceeds the data type.
And as alread said, I was able to fix the issue, when forcing 64 bit integers for radial_sum.

The error persists if I am using imageio to open the image instead of cv2.

**Comment by ma-sadeghi** [comment]
I see. It's because on Linux. According to [this](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine) stackoverflow thread, the default `numpy.int_` is C long, but C long is `int32` even Win64. 

Thank you for reporting this. We'll see what we can do to force `int64` as the default `int` type.

**Comment by kleinerELM** [comment]
Okay, thanks for your fast response and the nice libary!
