### ISSUE TITLE
network extraction sometimes builds throats between non connected regions

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#238]
This was brought up by @magnaou, so I'm capturing it here.

**Comment by TomTranter** [comment]
Could this be the same as #169 ?

**Comment by jgostick** [comment]
Don't think so.  Mehrez found that two regions which are not physically connected are somehow getting connected.  Probably due to the use of a structuring element that overlaps two regions, or something to that effect.  They are all related though.  We have *quite a few* network extraction related issues to deal with.  The last year has provided a lot of stress testing and revealed the bugs.

**Comment by megavolts** [comment]
I encountered the same problem as @jgostick.

I found those throats are often significantly longer than all the throat length distribution (4+ standard deviation away from the mean). When filtering them out, I also found that often the 2 last throats in the array were randomly generated. 

In addition, those throats are randomly generated. During my analysis, I looked at different vertical extend within the sample (0-25,0-50, ...), and an existing artifact throat appearing in the bottom 5 slices when analyzing 0-25 vertical slice, may disappear when analyzing the same sample from 0 to 50 slices.

I will be more than happy to share the dataset I've been currently working on. Attached 2 examples of artifact throats. Grey is the pore space (sea-ice micro-CT), yellow is throat network (after filtering out all pore space > mean+4std), blue is filtered out throats. The later are highlighted with a black circle. 

![02](https://user-images.githubusercontent.com/6134388/80921406-b6976100-8d22-11ea-8348-8b23df9f800e.png)

![01](https://user-images.githubusercontent.com/6134388/80921404-b5feca80-8d22-11ea-859d-db920ae25795.png)

**Comment by jgostick** [comment]
Hi @megavolts, I am not able to reproduce this error, in 2D or 3D.  Are you still willing to send me your data set?  You can email it to me at jgostick at uwaterloo dot ca.

**Comment by megavolts** [comment]
@jgostick, Sorry for the belated answer. I just emailed you one of the problematic datasets.  Let me know if you have any questions.

**Comment by jgostick** [comment]
OK, after having looked at your image, I have a feeling it is caused by 'lone' pores or bubbles.  I do not think the regions_to_network code has any special consideration for pores that have ZERO neighbors.  I am not sure how this would be handled exactly, but I am concerned that the code *assumes* each pore has at least one neighbor.  I will investigate further.

**Comment by megavolts** [comment]
That idea crossed my mind at some point, but it would not be a systematic issue, as some 'lone' pores don't have that problem. Thanks for keeping investigating further, I will be more than happy to continue testing for you.

**Comment by jgostick** [comment]
@megavolts I think we finally found this bug!  It was super subtle and not directly related to the apparent problem (long range connections).  Anyway, please download the latest dev and see if it helps.  When I run your image with the new version it looks good.
