### ISSUE TITLE
Parameters in generators.cylinders documentation are out of order 

### ISSUE THREAD

**Issue by 1minus1** [PMEAL/porespy#240]
Referencing: https://porespy.readthedocs.io/en/master/modules/generators.html#porespy.generators.cylinders

The function call has phi_max before theta_max, but the documentation has them reversed.

**Comment by jgostick** [comment]
Thanks, this one is easy to fix... unlike the regions props thing.  ;-)

**Comment by jgostick** [comment]
This is fixed in PR #245
