### ISSUE TITLE
Cylinders not randomly distributed in x-y plane from generators.cylinders

### ISSUE THREAD

**Issue by 1minus1** [PMEAL/porespy#244]
Due to some property of how random fiber locations are selected, fibers are more likely to cross near the center of the x-y plane versus point closer to the edge. This code makes a structure, then calculates the porosity at each x-y location.

```
import porespy as ps
import matplotlib.pyplot as plt
import numpy as np

im = ps.generators.cylinders([400,400,1000],5, 7000,0,90,None)
mean = np.mean(im,2)
plt.imshow(mean,cmap='plasma')
plt.show()
print(ps.metrics.porosity(im))

```
Results:
![image](https://user-images.githubusercontent.com/2090927/82471577-dd7cc380-9a94-11ea-9eb9-29943ebd32af.png)

A more dramatic example for a 1000x1000x1000 fiber image with a porosity of 0.5.

![image](https://user-images.githubusercontent.com/2090927/82471729-17e66080-9a95-11ea-8096-28e1600348ae.png)

**Comment by 1minus1** [comment]
One admittedly hacky workaround is to select a starting position for a fiber from a window much larger than the image. There is a chance that adding a fiber in this way won't actually add it to the region of interest (so the actual number of cylinders in the image will be less than the requested number) but the fibers are more randomly distributed in x-y.

in generators.cylinders
```
# Choose a random starting point in domain
        #x = sp.rand(3)*shape
        x = sp.rand(3)*shape*5-2*shape
```

For
`im = ps.generators.cylinders([100,100,100],1, 5000,0,90,None)`

Before hack:
![image](https://user-images.githubusercontent.com/2090927/82477694-cee6da00-9a9d-11ea-9afe-456772ae238f.png)
Resulting porosity = 0.654

After hack:
![image](https://user-images.githubusercontent.com/2090927/82477801-f6d63d80-9a9d-11ea-9cc1-1a5a050d15f1.png)
Resulting porosity: 0.747

**Comment by jgostick** [comment]
Damn, I actually thought that I'd fixed this.  It's been quite a while, but I know that I used to have the above issue, and I felt like my implementation (the one currently in porespy) fixed it, but I guess not.  Hacky workaround is ok, but is there a proper rigorous way?

**Comment by vasudevanv** [comment]
The sine and cosine normalization in lines 766-770 guarantee a uniform probability for each point within the box to be an origin point and the orientation of the fiber emanating from that point to have end points uniformly distributed on a sphere centered on the origin. But we clip the fibers to the box after this and the volumes of the intersection of spheres centered at each origin point with the image box are not same. Points in the center of the box have larger overlap while points at the edge have smaller overlap

**Comment by 1minus1** [comment]
I think I understand why it's not uniform. 

If I understand correctly, the way it is working is picking a random point in the box, random phi and theta in the specified range, and generating from there. What isn't guaranteed is that the points on the cylinder are uniformly distributed.

For any point (x1,y1,z1) that is the origin point for a cylinder of random orientation, there is a probability that a second point (x2,y2,z2) also lies within the cylinder. This probably is the ratio of the 2*sphere_cap_area/sphere_surface_area. So the probability of a point being in a cylinder for a randomly placed fiber is related to the integral of that probability for that point over the entire volume of origin points. This integral is not constant within the box, since on average, edge points are further away from most points than points at the center.

![image](https://user-images.githubusercontent.com/2090927/82500316-28accb80-9ac1-11ea-8c61-0cd2f5dd0b86.png)

**Comment by jgostick** [comment]
Yes you understand correctly, that is how I implemented it.  I played around with several ways to do it, but ultimately this was the only where I could come up with that let me pick random values of phi and theta within limited range to make anisotropic media.

I did consider do your proposed 'hacky' approach but I didn't want to expand the domain so much for speed reasons.  

I don't understand what this means: "What isn't guaranteed is that the points on the cylinder are uniformly distributed."

**Comment by jgostick** [comment]
@1minus1 I implemented something close to your quick fix in PR #245.   The starting points are generated over a much larger region now.  I basically increase the region by the requested fiber length on all sides.  Anything more than that would be point less since the the generated fibers would not reach that actual domain.  I did this without actually creating a larger image, which is good.  The down side, as you say is that more tries are required to get the correct number of cylinders.  The function was still decently fast on my laptop though, but I didn't compare times.  Let me know if this new version works better for you.  We can still discuss the porosity thing separately, but at least you'll have a valid function to build on!

**Comment by 1minus1** [comment]
> I don't understand what this means: "What isn't guaranteed is that the points on the cylinder are uniformly distributed."

I mean that the origin points you start with are uniformly distributed throughout the volume, but the points that are added in the rest of the cylinder are not.

**Comment by 1minus1** [comment]
The fix you put in PR #245 works well. Thank you!

For the same test case as above: 
![image](https://user-images.githubusercontent.com/2090927/82558906-b11c8200-9b3c-11ea-9347-515be061ef5b.png)

and for 

`im = ps.generators.cylinders([400,400,50],1, 10000,0,90,None)`

![image](https://user-images.githubusercontent.com/2090927/82558803-74e92180-9b3c-11ea-922b-d4eadb6cf3ac.png)

**Comment by jgostick** [comment]
I am going to merge this change into dev since you're ok with it.   I will close this issue now.

**Comment by 1minus1** [comment]
Thank you!
