### ISSUE TITLE
Allow n-phase segmentation to work even one of the labels is missing

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#246]
If a user gives an image with labels of 0, 1, and 3, but specifies an alias list of {0: solid, 1: void, 2: water, 3: PTFE}, the function should still work, despite there being no voxels labelled 2.   

The method should be flexible enough to handle this case, which could happen in automatic image processing scenarios, where the user expects there to be water but for whatever reason it is not present in a particular image.  Basically the user shouldn't have to check each image beforehand.

**Comment by Zohaib-Atiq** [comment]
@jgostick this has been resolved in porespy-private PR #13

**Comment by jgostick** [comment]
Fixed in #265
