### ISSUE TITLE
General updates to snow_partition_n

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#247]
There are 3 issues with this function at the moment, so I'm opening this 'meta' issue to combine all into a single place:

1.  #168 Some images do not have contiguously labelled regions (e.g. 22, 98, 255).  It would be nice if the alias function could handle this, perhaps by detecting this situation and relabeling the voxels in contiguous order before processing?  
2.  #246  Sometimes users may think their labels are contiguous but they are not, such as 0, 1, 3, where 2 is supposed to be water but the region that was imaged happened to be dry.  It would be nice if the function could handle this gracefully.
3.  #169 Lastly,there appears to be a bug if there happens to be no zeros in the image, so I guess the code is making a hard assumption about this that may not be true.

**Comment by Zohaib-Atiq** [comment]
@jgostick #168 and #246 has been resolved in porespy-private PR #13. 
I am working on possible solution of #169

**Comment by jgostick** [comment]
PR #265 is now merged and it fixes many of these.  Also, as @Zohaib-Atiq says, there are other changes in his private project
