### ISSUE TITLE
[Proposal] Add option to snow_partitioning to skip trimming saddle points or nearby peaks

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#255]
I know these two steps are basically what makes SNOW SNOW, but in some cases, it's beneficial to keep the regions over-segmented to better capture pore-scale physics. For instance, in network extract for the Nafion phase in fuel cell catalyst layers, we don't want to perform DNS, but using vanilla SNOW makes our Nafion representation too rough. It seems that skipping one or both of these steps (trim saddle points or nearby peaks) leads to a better representation of the Nafion phase.

While I can manually do this for my use case, I think it's a nice option to have. We can make the default mode to be turned off not break anybody's code.

**Comment by ma-sadeghi** [comment]
What do you think @jgostick?

**Comment by 1minus1** [comment]
I also wanted this, and found that that working around it was cumbersome. I implemented it, and made a PR: https://github.com/PMEAL/porespy/pull/258

**Comment by jgostick** [comment]
But trimming saddle points is the whole point!  :-)  Actually using a gaussian blur also helps a lot, but saddle points were the 2nd most important part.  In fact, I would suspect that your extraction is over-segmented unless you remove these, so maybe triple check you really need to.  Especially in high porosity media.

**Comment by 1minus1** [comment]
I agree that SNOW is likely best for high porosity media. My only point in using these options is to check against the simpler segmentation methods. My previous PR was set up incorrectly, so I've re-submitted as https://github.com/PMEAL/porespy/pull/260

**Comment by jgostick** [comment]
this is not necessary since you can just call each function separately
