### ISSUE TITLE
Alias map in SNOW_N is sensitive to dtype: float/int

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#259]
It breaks when the passed alias dtype differs from that of the image, i.e. 1.0 vs 1

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi  I passed `alias = {1.0: 'am', 2.0: 'elec'}` and it worked for me. Can you share SNOW_N code where you are passing this info. 
Also I have changed _create_alias_map alot. I have checked in newer implementation also its working fine for me.

**Comment by jgostick** [comment]
I have merged PR #265 so I think this problem is fixed on that PR
