### ISSUE TITLE
SNOW algorithm returns network with a different shape than the original 3d image.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#26]
When I pass a (1, 500, 500) 3d image to SNOW, it returns a network with z-values = 0. Rather, I expected that it would return a network with x-values = 0.

**Comment by jgostick** [comment]
You need to set z to 0...this is hard coded into the code....even scipy.ndimage assumes the first dim is not flat.

**Comment by ma-sadeghi** [comment]
I see, but this makes it impossible to overlay the two networks in Paraview since the two are in different planes. The workaround would be to remap `pore.coords` of either of the two networks.

**Comment by jgostick** [comment]
There is a method network_extraction called 'align_with_openpnm' to solve this temporarily

**Comment by jgostick** [comment]
Are you saying that setting the first axis to 1 will make all these things line up properly? ! It's been super annoying trying to deal with this.

**Comment by ma-sadeghi** [comment]
No, still the image needs to be rotated. They are two different issues. One is with regards to the rotation, and the other one is about coplanarity. When you pass a 3d image in the yz plane, the extracted network is still on the xy plane, which makes it impossible to overlay in Paraview.

**Comment by jgostick** [comment]
It's definitely not impossible...I've done it many times.  You need to flip and rotate the image just the right way.  I thought that the align_with_openpnm function did this for 2d and 3d images...no?

**Comment by ma-sadeghi** [comment]
Yes, it's doable, I meant if you load the two networks without modifying, they're in two different planes. `align_with_openpnm` works fine I guess.
