### ISSUE TITLE
Axes convention for SNOW boundary labels differs from that in OpenPNM

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#261]
SNOW: "left" and "right" are along the x-axis, whereas in OpenPNM they are along the y-axis.

@jgostick Was this on purpose?

**Comment by jgostick** [comment]
Don't think so.  We should fix this in V2.  Zohaib may have done it to help things line up in paraview.

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi @jgostick  I did it because it is aligned with paraview. I suggest we should update openpnm 'left' and 'right' as its seems to be a bug there. Paraview is like our default visualization tool.

**Comment by Ni2M** [comment]
I think we fixed OpenPNM convention in https://github.com/PMEAL/OpenPNM/issues/1575 to right hand rule. It should be consistent now.

**Comment by ma-sadeghi** [comment]
@Ni2M Could you please check if this is fixed? (please check w/ both OpenPNM and porespy). Feel free to close it if it is.

**Comment by Ni2M** [comment]
Sure.

**Comment by Ni2M** [comment]
We fixed OpenPNM's problem to be consistent with right hand rule: https://github.com/PMEAL/OpenPNM/pull/1660, I checked OpenPNM with PoreSpy. Their front,back labels are not consistent. PoreSpy considers front with lower Y and back with higher Y
https://github.com/PMEAL/porespy/blob/de7020f576c45544af02fe51c1162cdbeb90afa6/porespy/networks/__funcs__.py#L434
, whereas OpenPNM considers back with lower Y and front with higher Y

https://github.com/PMEAL/OpenPNM/blob/743707ddcf56c4e229c95ff528210eae3b42ea73/openpnm/network/Cubic.py#L210

I tried with an example as well. I'll take a closer look into it and fix the problem.

**Comment by ma-sadeghi** [comment]
@Ni2M I think the approach used in `OpenPNM` is the correct one. Could you please look into `porespy` and create a PR?

**Comment by Ni2M** [comment]
Thank you Amin. Right, both of them should follow right hand rule. Sure.

**Comment by Ni2M** [comment]
Referring to https://github.com/PMEAL/OpenPNM/issues/1575#issue-655943861, based on provided right hand rule image, front face is at y<=0 (closer to the viewer's eyes) and back face is at y>0 (farther from the viewer's eyes) and that's similar to PoreSpy.  If we want to follow this image (right-hand rule) as a reference, I think I should change OpenPNM's approach on y axis instead.

OpenPNM's earlier issue was fixed on changing x,y axis references to carry left/right and back/front. I think their front,back labels are still not consistent with right-hand rule. https://github.com/PMEAL/OpenPNM/pull/1660#issuecomment-699215014

**Comment by ma-sadeghi** [comment]
@Ni2M Right, we should flip OpenPNM's front and back. Nice catch.

**Comment by Ni2M** [comment]
Thanks. I will open a PR in OpenPNM.

**Comment by Ni2M** [comment]
We are closing this issue. It is addressed in OpenPNM.
