### ISSUE TITLE
Make porespy-examples repo private

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#262]
@jgostick

**Comment by jgostick** [comment]
Quick question: the reason we moved the examples INTO the main repo was so they would be tested at the same time as the main code.  Now that we have a lot more power with Actions, could we trigger a build of the porespy-examples repo from the main porespy repo?  For instance, if we setup porespy to automatically deploy to Pypi, could we also run the porespy-examples tests.  I looked into this before and it was quite tricky but maybe this has changed?

**Comment by ma-sadeghi** [comment]
@jgostick In principle, this should be doable with Actions. But, do we really want to maintain a separate repository for examples? Especially that `porespy-examples` has been out of date for quite some time, so not sure if anybody is actively using it.

**Comment by jgostick** [comment]
done
