### ISSUE TITLE
More precise labelling for snow_n and snow_dual algorithms

### ISSUE THREAD

**Issue by Zohaib-Atiq** [PMEAL/porespy#264]
`snow_dual` and `snow_n` return `pore.left` and `pore.right`, etc. but if we have two or more phases each phase should have unique boundary key. For example `pore.left_phase1` and `pore.left_phase2`, etc.

**Comment by ma-sadeghi** [comment]
Is this necessary? Can't the user do `net.pores(["left", "phase_1"], mode="and")`

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi net.pores(["left", "phase_1"], mode="and")? will give you `array([], dtype=int32)` because the throats are associated with `phase1` and not `pn.pores('left')`

**Comment by ma-sadeghi** [comment]
:thumbsup I see, then I think it's definitely a nice thing to have as I'm already doing this manually for the catalyst layer PNM.

**Comment by jgostick** [comment]
this now works on the new branch.
