### ISSUE TITLE
Specify different voxelsize for each direction - snow algorithhm

### ISSUE THREAD

**Issue by davidbhr** [PMEAL/porespy#268]
Hi, 

I am trying to extract the pore size of collagen networks by using the snow algorithm. I was wondering if it might be possible to specify the voxelsize seperatley for the different directions instead of using the same value for x,y-, and z-direction? Thanks for the help and best regards, david

**Comment by ma-sadeghi** [comment]
Hi @davidbhr, why don't you zoom your image to make it isotropic and then pass it to SNOW?

You can do this via 
```python
import scipy.ndimage as ndimage
ndimage.zoom(image, zoom=[1, 2, 3])
```

I think it's possible to modify SNOW to accept anisotropic voxel size, @jgostick knows more.

Btw, #71 is a related issue.

**Comment by jgostick** [comment]
No, the functions do not support anisotropic voxels.  @ma-sadeghi's suggestion of using the zoom function is our only tool for this.  Sorry.  My only suggestion would be to set the ``order`` parameter to 0, so is does nearest neighbor interpolation instead some fancy and extremely time consuming spline stuff.  Assuming your data comes from FIB-SEM, you probably have x and y resolution of 1 nm and z resolution of 25 nm, so you'll want to zoom the z-axis by 25x.  If this makes your image unmanageably large you could sacrifice some resolution in the x-y axes, so do: ``im = ndimage.zoom(im, zoom=[0.5, 0.5, 12.5], order=0)``.  Then you'll have 2nm voxels in each direction.

**Comment by davidbhr** [comment]
Hi @jgostick and @ma-sadeghi ,

Thanks for the quick reply, I am now using the zoom function to create an isotropic image stack. Since the voxel size in z-direction is only slightly higher compared to x,y, the interpolation works well and quick (images are derived from confocal reflection microscopy). Thanks for your help :)
