### ISSUE TITLE
Can i use my 3D volumetric data ?

### ISSUE THREAD

**Issue by shirongpei** [PMEAL/porespy#281]
I have simulated 3D volumetric data in which the gray scale (1 for solid, 0 for pore) at each grid point (x,y,z) is defined

Can i import the data for pore feature analysis?

Thank you!

**Comment by jgostick** [comment]
Yes of course!  I prefer to use ``imageio.volread`` to import 3d images like 'tif' images.  If your data is not in 'tif' format you should use imagej to open your data and convert to 'tif' images.

To study the pore phase you'll want to invert the image to set the pores to 1 and solid to 0, using ``im = ~im``.

**Comment by shirongpei** [comment]
Many thanks for your prompt response. I really appreciated it.

I don't start from a 3D image or a stack of 2d images. Instead, i started from 3d volumetric scalar data, please see blow.
I guess there is a way to import the txt file?

Thank you!

# x, y, z, scalar
   1   1   1      0.00
   2   1   1      0.00
   3   1   1      0.00
   4   1   1      0.00
   5   1   1      1.00
   6   1   1      0.00
   7   1   1      0.00
   8   1   1      0.00
   9   1   1      0.00
  10   1   1      1.00

**Comment by jgostick** [comment]
Anything is possible.  Assuming your data is in a text file called 'data.txt': 
```
import numpy as np
x, y, z, v = (np.loadtxt('data.txt').T).astype(int)
im = np.zeros(shape=[Nx, Ny, Nz], dtype=bool)
im[x, y, z] = v
```

**Comment by jgostick** [comment]
@shirongpei ... did my suggestion work?  Can I close this?

**Comment by shirongpei** [comment]
yes, worked perfectly. Thanks a lot
