### ISSUE TITLE
For the example of porespy/examples/networks/snow_basic.ipynb, how did you visualize spherical particle of different size

### ISSUE THREAD

**Issue by shirongpei** [PMEAL/porespy#286]
using snow_basic.ipynb, i generated im.vti and extraction, vtp,

How to use extraction.vtp in paraview to show pores of different equivalent diameter?

Thanks!

**Comment by jgostick** [comment]
https://openpnm.readthedocs.io/en/master/getting_started/visualize_in_paraview.html
