### ISSUE TITLE
How to visualize pores in spheres with esd? 

### ISSUE THREAD

**Issue by shirongpei** [PMEAL/porespy#287]
For the example of porespy/examples/networks/snow_advanced.ipynb

how did you add spheres of esd? How did you make it using paraview?

Thank you

![image](https://user-images.githubusercontent.com/49130449/90207322-cfd89080-dd9a-11ea-9749-483a2330e52d.png)

**Comment by ma-sadeghi** [comment]
What do you mean by ESD?

**Comment by shirongpei** [comment]
Thanks for your prompt response. ESD means equivalent sphere diameter. I think the size and color of those spheres are related to esd? thanks

**Comment by ma-sadeghi** [comment]
If your question is "how to generally generate such figure using ParaView", then [this](https://openpnm.readthedocs.io/en/master/getting_started/visualize_in_paraview.html) might help. Let me know if it works for you.

**Comment by shirongpei** [comment]
there is one vtp and one vti generated after running the code. The former is for the pore net work . I know how to use paraview. Just not quite sure, how did you visualize spheres when using paraview.

Thanks

**Comment by shirongpei** [comment]
sorry, did not realize "this" is a link. Thanks
