### ISSUE TITLE
A question about snow_basic.ipynb

### ISSUE THREAD

**Issue by shirongpei** [PMEAL/porespy#289]
I run the code below and the result is attached.  It seems that i did not capture all the pores?

Thank you!

https://github.com/PMEAL/porespy/blob/master/examples/networks/snow_basic.ipynb

![Picture1](https://user-images.githubusercontent.com/49130449/90307725-de53a480-de8d-11ea-90ec-a4aa47890a26.png)

**Comment by ma-sadeghi** [comment]
I just recorded a pseudo-tutorial on how to do this on [YouTube](https://youtu.be/gv7g1XlbF7U).

**Comment by shirongpei** [comment]
I really appreciated your efforts. It worked. It turned out that the Under Masking the Gyph Mode should be "All Points".

By default it was "uniform distribution"

Thanks again!

**Comment by ma-sadeghi** [comment]
No worries
