### ISSUE TITLE
How to distinguish internal pores and pores at boundary?

### ISSUE THREAD

**Issue by shirongpei** [PMEAL/porespy#292]
I run the example at  https://github.com/PMEAL/porespy/blob/master/examples/networks/snow_basic.ipynb

Please see below for the pore properties.

I am wondering if one can distinguish pore.internal and pore.boundary  and if so, how to retrieve diameters of both internal pores and pores at boundaries. So far, what i can do is print(pn['pore.diameter']) for all the pores.

Thanks!

Rongpei

print(pn)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
openpnm.network.GenericNetwork : net_01
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#     Properties                                    Valid Values
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
1     pore.area                                       253 / 253  
2     pore.centroid                                   253 / 253  
3     pore.coords                                     253 / 253  
4     pore.diameter                                   253 / 253  
5     pore.equivalent_diameter                        253 / 253  
6     pore.extended_diameter                          253 / 253  
7     pore.inscribed_diameter                         253 / 253  
8     pore.label                                      253 / 253  
9     pore.surface_area                               253 / 253  
10    pore.volume                                     253 / 253  
11    throat.area                                     276 / 276  
12    throat.centroid                                 276 / 276  
13    throat.conduit_lengths.pore1                    276 / 276  
14    throat.conduit_lengths.pore2                    276 / 276  
15    throat.conduit_lengths.throat                   276 / 276  
16    throat.conns                                    276 / 276  
17    throat.diameter                                 276 / 276  
18    throat.direct_length                            276 / 276  
19    throat.endpoints.head                           276 / 276  
20    throat.endpoints.tail                           276 / 276  
21    throat.equivalent_diameter                      276 / 276  
22    throat.inscribed_diameter                       276 / 276  
23    throat.length                                   276 / 276  
24    throat.perimeter                                276 / 276  
25    throat.total_length                             276 / 276  
26    throat.volume                                   276 / 276  
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#     Labels                                        Assigned Locations
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
1     pore.all                                      253       
2     pore.back                                     11        
3     pore.bottom                                   12        
4     pore.boundary                                 47        
5     pore.front                                    12        
6     pore.internal                                 206       
7     pore.left                                     13        
8     pore.right                                    12        
9     pore.top                                      11        
10    throat.all                                    276       
11    throat.boundary                               47        
12    throat.internal                               229       
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by ma-sadeghi** [comment]
You should probably take a look at our OpenPNM tutorials located [here](https://github.com/PMEAL/OpenPNM/tree/dev/examples/tutorials).

In the meantime, let's say your boundary pores are labeled as "pore.boundary". You might find the following code snippet useful.

```python
boundary_pores_indices = net.pores("boundary")
non_boundary_pores_indices = net.pores("boundary", mode="not")
pore_diameter = net["pore.diameter"]
boundary_pores_diameter = pore_diameter[boundary_pores_indices]
non_boundary_pores_diameter = pore_diameter[non_boundary_pores_indices]
```

I'm not sure if this answers your question.

**Comment by shirongpei** [comment]
Yes. it worked. Thanks a lot!
