### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by alexeytopolnitskiy** [PMEAL/porespy#305]
Hello! I installed the library using pip install and then tried to import but the system returned me an error. I am working in Linux OS. Does anyone know how to solve it?

<img width="1059" alt="Снимок экрана 2020-09-21 в 12 16 48" src="https://user-images.githubusercontent.com/41486841/93750639-7880d800-fc04-11ea-845f-cd38ba48b3d0.png">

**Comment by ma-sadeghi** [comment]
This seems like a `numpy` issue. Try updating your `numpy`. Btw, do you use Anaconda?

**Comment by jgostick** [comment]
that would be terrible if they stopped maintaining edt...that package is essential.

**Comment by ma-sadeghi** [comment]
> that would be terrible if they stopped maintaining edt...that package is essential.

I don't think so, I just successfully installed `porespy` on a fresh virtualenv on Linux. I've seen that error before, it's very likely coming from `numpy`. Upgrading (in rare cases, downgrading) `numpy` fixes the problem.

However, when trying to reproduce the error, I realized our `dask` version in `setup.py` is not quite right. For some reason, we need `dask[complete]` for `pip`, but `dask` is enough for `conda`.

We need a hotfix for those using `pip`.

**Comment by alexeytopolnitskiy** [comment]
Thanks for replies! I solved the problem by updating anaconda. It turned out that I had python 3.7 so I updated to the latest version of anaconda. Then I used **conda install -c conda-forge porespy** command and boom! Everything is working well. There is no error when importing.
