### ISSUE TITLE
What is the return of pore_size_distribution

### ISSUE THREAD

**Issue by miniminisu** [PMEAL/porespy#310]
It's difficult for me to understand the curve of psd. 
![curve](https://user-images.githubusercontent.com/34959179/94344434-ff451300-0051-11eb-95a7-9c0a74a085a1.png)
There are some question botherd me:

1. Does the x-axis means pore size ?
2. What about the y-axis ?
3. Why does the y-axis value start at 1 ?
4. As the radius gets larger, why does the y-axis get smaller and smaller, and finally approach zero?
5. Which one should I choose between pdf and cdf ? I wanna make the curve of pore size distribution of my data.

@jgostick @Zohaib-Atiq

**Comment by jgostick** [comment]
The above curve basically tells you "the volume fraction of the void space that is filled by spheres of a given radius (in voxels)"  So it looks like if you use spheres of radius 9, you can fill about 50% of the void space, meaning the other 50% is too small to fit such a sphere.  It might help to imagine that this graph is generated from right to left, so larger spheres (i.e. 30 voxels) are inserted first, and not many can fit, then progressively smaller spheres are used.  Eventually spheres with radius 1 are used and they can fit every where, hence the y-axis reaches 1.0, or 100% filled.  You can look at the pdf as well, which shows the 'histogram'-type version, where there is a peak at the 'mean pore size'.

**Comment by jgostick** [comment]
fyi, you can also convert the size to capillary pressure, meaning that low pressure are invaded first, so the above curve will increase from left to right.  The above result is analogous to mercury intrustion porosimetry.

**Comment by miniminisu** [comment]
I get it. Thanks a lot!!!
