### ISSUE TITLE
SNOW extraction with optional zoom for select phases

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#314]
The idea is to tell SNOW which phases to zoom and by how much. This is useful when dealing with multiphase images in which one (or more) phase(s) is low resolution. 

A good example is fuel cell catalyst layers where the void and carbon phases are typically large blobs and therefore don't need that much zooming. On the other hand, zooming the Nafion films would substantially improve the network extraction.

**Comment by jgostick** [comment]
I'm going to remove this from our list of urgent network fixes, since it's a nice to have, not a must have.
