### ISSUE TITLE
Improving unit tests for network extraction functions

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#317]
Some of our methods are not properly being tested by our unit tests. I only skimmed through `test_network_extraction.py`, and it seems that we're not properly testing network extraction. From what I see, most of the time, we're only checking the shape of the output, whereas at the very least, I think we should check the values.

**Comment by ma-sadeghi** [comment]
A good way to test the output value(s) of a function is to compare its `np.linalg.norm`, which sort of uniquely encapsulates the image values.

**Comment by jgostick** [comment]
I'm going to move this to a 2.1 issue.  It's obviously important, but I think that a good thorough sweep of the unit tests is needed and that will take time and delay the release of 2.0.

**Comment by jgostick** [comment]
I have added buncha tests for the extractions.  They check for exact numerical outputs, like the right number of peaks, regions, etc.
