### ISSUE TITLE
regionprops_3D

### ISSUE THREAD

**Issue by hsafari68** [PMEAL/porespy#319]
When tried to get the properties on a 3D carbonate image labeled by snow for a 600 by 600 by 150 volume, the function was very very slow and I got the following error every time and ofcourse a couple of other errors. 
But when I tried the regionprops method in skimage, results were returned pretty fast without error.

Error:
QhullError: QH6013 qhull input error: input is less than 3-dimensional since all points have the same x coordinate    0

While executing:  | qhull i Qt
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 236552816  incidence  Qtriangulate  _pre-merge  _zero-centrum
  _max-width  4  Error-roundoff 5.5e-15  _one-merge 3.9e-14
  _near-inside 1.9e-13  Visible-distance 1.1e-14  U-max-coplanar 1.1e-14
  Width-outside 2.2e-14  _wide-facet 6.7e-14  _maxoutside 4.4e-14

**Comment by hsafari68** [comment]
It works on smaller subvolumes, but crashes on larger ones

**Comment by jgostick** [comment]
Quite honestly, this function is a bit obsolete now.  I wrote it back before scikit-image had proper 3d support in this function.  Is there something specific you're looking for that is not in scikit-image?

**Comment by jgostick** [comment]
also, that particular error means that the region is flat, like 2d...qhull does not like that.

**Comment by hsafari68** [comment]
> 
> 
> Quite honestly, this function is a bit obsolete now. I wrote it back before scikit-image had proper 3d support in this function. Is there something specific you're looking for that is not in scikit-image?

I actually used regionprops_3D for 2D images and it worked quite well. It gave me a couple of other properties than skimage regionprops function like sphericity, but that's not a big deal. 
What I liked was the props_to_DataFrame method that I used to convert all the returned proeprties to a data frame in Python, but unfortunately that also seem not to be working giving me the same errors as regionprops_3D did. These functions seemed to be quite handy in 2D images, but I assume I have to write a couple of lines of codes to handle these calculations for my case unless you would want to update these functions in the porespy package.

**Comment by jgostick** [comment]
ok, I'm on it.  But first, are you sure that you just don't have an anomalous image?  Does it work as desired with other 3D images?

**Comment by hsafari68** [comment]
I would really appreciate it if you do because I have found porespy and openpnm very powerful packages in digital rock physics.
Actually I haven't tested it on other 3D images yet, but I did perform the same analysis on my image using the Avizo software and the same as skimage regionprops method, the results were returned pretty fast. At first, I thought maybe this is because my image is from a carbonate sample and highly heterogeneous, but several other functions on porespy package work quite well on the iamge except the two aforementioned methods.

**Comment by TomTranter** [comment]
The line that triggered the qhull_error might need to pass qhull_options="QJ Pp". That's what I do for 2d convexhulls. Alternatively maybe some of the parameters for network extraction need tweaking to avoid over segmentation. Also if it's purely 2D then the region will be aligned with a boundary and probably is on the boundary itself so you could try padding the image after extraction with mode "edge" using numpy.pad

**Comment by hsafari68** [comment]
Actually, now that I'm thinking, I did the calculations on different subvolumes, and the regionprops_3D failed only on some of those regions. I am not sure but maybe there is something in those images that triggers the qhull_error.

I could share my 3D image with you if you want. Just give me an email address.

**Comment by TomTranter** [comment]
Can you try my suggestion to pad it first then I'll have a look

**Comment by hsafari68** [comment]
> 
> 
> Can you try my suggestion to pad it first then I'll have a look

I did pad my image by changing the mode to 'edge' in the source code. It gave me two errors, the first one is that skimage.measure.regionprops no longer supports coordinates. I fixed the first one. But then the second error popped up which is our friend "qhull_error."

**Comment by TomTranter** [comment]
https://github.com/PMEAL/porespy/blob/dev/examples/networks/snow_advanced.ipynb
This tutorial gives you a step by step guide to the network extraction. If you run the snow algorithm it will do everything for you and accept all the defaults but if you go through step by step you might be able to find where things are going wrong easier. I suspect that the image contains rough features which are causing it to over-segment. You could try different values for sigma in the gaussian filter or maybe some of the other parameters... https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter.html
You could also try to clean up the image a bit beforehand with some binary opening and closing which can improve rough edges and close small holes.

**Comment by jgostick** [comment]
Great news.  I finally got around to making our regionprops act like skimage, so it only generates the value on demand.  I was over thinking it BIG TIME.  I thought they were using like delayed dispatch to multiple cores and yadda yadda yadda but they just fill the the list with a bunch of object handles that have the functions as attributes.  I inherited their base class and added our own attributes.

**Comment by jgostick** [comment]
Sooo, funnily enough, it turns out this qhull error is actually not coming from porespy's regionprops. If you pass the offending image into the skimage regionprops, AND request the convex_area of the offending region(s), you'll get the QhullError.  The reason you see it in porespy is that we actually executed the convex_area method for each region. (Note, my recent PR fixes this so that now it doesn't execute any methods until the property is asked for).  I noticed this because I was going to augment our function to catch that exception, when I realized we only wrap convex_area to call it convex_volume (to make things more clear since it is for 3D images).  Anyway, I think I'll leave things as they are and that PR is now ready to be merged.  

@hsafari68 are you able to download that branch and test it out on your image?  I recently wrote some instructions for how to download specific branches from the github repo [here](https://github.com/PMEAL/OpenPNM/blob/dev/examples/notebooks/tutorials/using_and_contributing_to_the_dev_version.md),  These instructions are for openpnm, but they apply to porespy too.

**Comment by hsafari68** [comment]
@jgostick  @TomTranter  I appreciate all the help and support you provided. And thank you @jgostick  for taking the time to fix this problem. I am certain that this will definitely solve the issue with my image. Thank you for the helpful instructions.

**Comment by VolkerH** [comment]
> 
> 
> Great news. I finally got around to making our regionprops act like skimage, so it only generates the value on demand. I was over thinking it BIG TIME. I thought they were using like delayed dispatch to multiple cores and yadda yadda yadda but they just fill the the list with a bunch of object handles that have the functions as attributes. I inherited their base class and added our own attributes.

Just came across this discussion. Probably too late now, but the upcoming version 18 of skimage will have an `extra_properties` argument, where one can pass in functions to be calculated on the regions. This offers an easy way to add attributes. https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.regionprops
