### ISSUE TITLE
MemoryError - PNM generation

### ISSUE THREAD

**Issue by p-thomson** [PMEAL/porespy#321]
Hi all, 

I think this is more of a hardware issue but I thought I would post it here as you may have come across it and may know of an alternative solution to upgrading my RAM. I am running the below script to generate a PNM from a 3D tif image. The image has 6 um voxel resolution and the domain is 1000x1000x3000 voxels. I am working on ubuntu and when I run the script I receive the following error message:
"MemoryError: Unable to allocate 67.1 GiB for an array with shape (3, 3000, 1000, 1000) and data type float64". My workstation has 125 gb memory and I have tried permitting more access to the memory using the overcommit_ratio but with no luck. 

Have you come across this issue before? Is there an alternative to more RAM or is there something else I can try?

`import os
import imageio
import scipy as sp
import numpy as np
import openpnm as op
import porespy as ps
import matplotlib.pyplot as plt
from openpnm.io import OpenpnmIO

np.set_printoptions(precision=4)
np.random.seed(10)
#matplotlib inline

path = 'sample_6_um/3D_tiff' ### path to raw 3D tif image
file_format = '.tif'
file_name = '1000x1000x3000.inverted_6_um'
file = file_name + file_format
fetch_file = os.path.join(path, file)
im = imageio.mimread(fetch_file, memtest=False)
im = ~np.array(im, dtype=bool)

print(ps.metrics.porosity(im)) 

#NBVAL_IGNORE_OUTPUT
resolution = 6.0E-06
net = ps.networks.snow(im=im, voxel_size=resolution)

ws = op.Workspace()
proj = op.Project()
pn = op.network.GenericNetwork(name=file_name, project=proj)
pn.update(net)  # Fills 'pn' with data from 'net'

OpenpnmIO.save_project(project=proj, filename=file_name) 

print(pn)`

Many thanks,

Paul

**Comment by p-thomson** [comment]
Update: I managed to generate the (834x834x3000) PNM on a workstation with 256 GB RAM, however it still produced a warning message - "Maximum number of iterations reached, consider running again with a larger value of max_iters". Do you know where I would find the option to increase the iterations?

**Comment by TomTranter** [comment]
Hi @p-thomson this will be in the trim_saddle_points function which is called as one of the steps. You might want to look at this example to do things step by step individually https://github.com/PMEAL/porespy/blob/dev/examples/networks/snow_advanced.ipynb

**Comment by p-thomson** [comment]
Thank you, I'll take a look

**Comment by jgostick** [comment]
That message is not that important...and I find it usually means something is wrong with the image, like it was a greyscale image or was binary, but not in boolean form.

**Comment by jgostick** [comment]
Note that there was also an issue in the ``make_contiguous`` function.  I had been making too many copies of the arrays for the sake of speed, but the memory ballooned.  We now use the ``relabel_sequential`` function from skimage under the hood, so things are still as fast, but use much less memory.
