### ISSUE TITLE
Different extracted networks from a same image

### ISSUE THREAD

**Issue by Abolfazlmsl** [PMEAL/porespy#336]
Hi, I extracted the network of an image successfully. but when I extracted the network from this image again, the network became a little different from the previous one. Why would this happen? and how I can extract a same network from an image in different running? 
Thanks for your help.

**Comment by jgostick** [comment]
This should not happen, but is almost certainly the result of changing versions somewhere in the software stack.  I assume that you're comparing two versions that have been extracted at different times?  If you're getting different results on exactly the same machine just minutes apart, then something odd is happening.  Can you clarify?  Also, how 'different' are things?

**Comment by Abolfazlmsl** [comment]
Thank you Dr.Gostick,
No, I am using one version of Porespy (Porespy 1.2.0). I extracted the Berea sandstone network with dimensions of 400,400,10 several times but the porosity and permeability obtained differently from each other a bit. So, I sorted the pore and throat diameters of each extracted network in a file and saw two or three differences in the pore or throat sizes. Also, in the exported .vtp file of two realizations, the differences are obvious.
![Capture](https://user-images.githubusercontent.com/41609766/103267138-5e565300-49c6-11eb-96f8-99301ca22385.PNG)
![Capture1](https://user-images.githubusercontent.com/41609766/103267166-6a421500-49c6-11eb-80db-16501f0b2ff3.PNG)

**Comment by jgostick** [comment]
The only place that I can think of with randomness is the ``randomize_colors`` function, which is used to make "mix" the region colors up for easier visualization.  I will check to see if there is a bug in there.

**Comment by jgostick** [comment]
Also, porespy is at version 1.3.1 now, so I suggest you upgrade.  We have squashed a few bugs, so maybe this problem will go away.  Can you try that asap and let me know if the problem persists?

**Comment by Abolfazlmsl** [comment]
Thank you.
Yes, I checked the newest version today but the problem persisted.

**Comment by Abolfazlmsl** [comment]
I set the randomize_colors=False and the problem fixes. Now all the extracted networks are same.

**Comment by ma-sadeghi** [comment]
@Abolfazlmsl I'm closing this issue, if you have more questions, feel free to reopen.
