### ISSUE TITLE
Calculate fractal properties

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#37]
It's relatively easy to calculate the fractal dimension of an image.  Just count the number of 1's and 0's in boxes of different size.  This could be done with a convolution filter in about 3 lines!

There is also lacunarity and succolarity.  These latter two are similar to fractal, but done on different versions of the base image.

**Comment by TomTranter** [comment]
I'd be interested in developing this. As I mentioned I think the fractal dimension will relate to the importance of Knudsen diffusion and it could be interesting to explore with pytrax
