### ISSUE TITLE
Expose parallelization arguments?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#380]
We have enabled dask chunked parallelization on several functions.  It's possible to trigger this if you know the magic keyword args to input, but it's not obvious (i.e. documented in the docstrings).  We should probably add this.

**Comment by ma-sadeghi** [comment]
@jgostick How about controlling it in the settings? Either turn on parallelism for all methods or none.

**Comment by jgostick** [comment]
meh, not sure about that.  You probably don't always want that.  Actually, you could do:

```
ps.settings.parallel = {'cores': 8, 'divs': 2}  # Sensible default settings
filt = ps.filter.blah(im=im, parallel=ps.settings.parallel)
```

**Comment by jgostick** [comment]
So we'd change the api to all functions to accept a ``parallel`` argument which is a dict containing the parameters, which *can* be retrieved from the settings where sensible default values live, or users can just pass in their own dict.

**Comment by jgostick** [comment]
Alternatively, the argument could be ``parallel=True``, and if ``True`` then the function looks into the settings to get the parameters.  The trouble with this case is that you don't have fine control over the params on per function basis.  There may be a function that uses a lot of ram so you'd want cores =1, while a function that is just really slow you'd want cores=8.

**Comment by ma-sadeghi** [comment]
Why is that? Are there cases where parallel execution is significantly slower than serial? I know that for small images, the overhead of parallel execution makes it run slower, but in those cases, the total execution time is small enough that the user won't even notice the difference. For large images, though, parallel execution should always be faster, isn't that the case?

**Comment by ma-sadeghi** [comment]
I just read your last comment. For those functions with high memory requirements, when we chunk up the image, wouldn't that also linearly decrease the memory usage?

**Comment by jgostick** [comment]
If you do chunks, but set cores to 1 it processes them serially. I needed to do this for some FFT based convolutions since they seem to create arrays in the background that consumed lots of memory.

**Comment by ma-sadeghi** [comment]
I see your point. What I was trying to convey is that we should have good default values (maybe change default values for fft?) so that `porespy` is fast enough for most users, without having to manually decide what to pass for those arguments.

Like how `umfpack` is always using all cores w/o user explicitly defining the number of processes, while you can still use `umfpack` on 1 core by setting the environment variable `OMP_NUM_THREADS` to 1.
