### ISSUE TITLE
Persistent settings between sessions?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#384]
This would be very helpful.  Nosql maybe?

**Comment by ma-sadeghi** [comment]
What do you mean?

**Comment by jgostick** [comment]
You might want to set some values different than the default, and have them repopulate the next time you start Spyder.  if we stored them in a nosql or sqlite database, we could load them each time.

**Comment by jgostick** [comment]
this is more trouble than  its worth.
