### ISSUE TITLE
Improve ImageJ submodule to run in headless mode

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#393]
See [here](https://github.com/imagej/pyimagej/issues/102) for more details.

**Comment by ma-sadeghi** [comment]
We've also forced unit tests to only run for Windows. This should also be removed once this issue is dealt with.

**Comment by ma-sadeghi** [comment]
For future reference: https://javadoc.scijava.org/ImageJ/net/imagej/ops/image/watershed/Watershed.html

**Comment by jgostick** [comment]
Given that the imagej functions offer only minimal or zero performance improvements, we should probably not invest much more time into this module, and probably deprecate it in v3 down the road.

**Comment by ma-sadeghi** [comment]
It seems that the issue has been fixed [upstream](https://github.com/imagej/pyimagej/issues/126). Also, it seems that the speedup is [real](https://github.com/PMEAL/porespy/discussions/662#discussioncomment-2421405) after all, and it's almost an order of magnitude (at least for some filters). So, I'd say let's reopen this issue.

**Comment by jgostick** [comment]
I don't think this is something porespy needs to manage for people.  If they want to use imagej funcs from within python, they can figure it out.
