### ISSUE TITLE
Rename double underscore names?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#398]
I recently bumped into a PEP8 guide for naming convention, and it strongly discourages using double underscores other than those offered by Python (e.g., init, etc.).

> __double_leading_and_trailing_underscore__: "magic" objects or attributes that live in user-controlled namespaces. E.g. __init__, __import__ or __file__. Never invent such names; only use them as documented.

https://www.python.org/dev/peps/pep-0008/#id36

We use these underscores quite often. `__imgen__` could be turned into `imgen`, for instance.

**Comment by jgostick** [comment]
I'm not sure if pep8 applies to file names.  We used the double underscores because if we don't the module path becomes ``porespy.generators.imgen``.  If you can find a work around for this, then go for it.

**Comment by jgostick** [comment]
After consulting a few major packages it seems that all files should start with a single underscore. Also it's probably a good idea to use the ``__all__`` magic inside each file so the imports can be simplified to ``from ._blah import *``.

**Comment by jgostick** [comment]
We'll do this for V2 for sure, but will wait until ALL PRs and loose ends are tied up.  It might not be a bad idea to divide up the files by function category a bit too while we're at it.
