### ISSUE TITLE
More robust determination of notebook vs. terminal-based progress bar

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#399]
Need to replace this line:
https://github.com/PMEAL/porespy/blob/ec0b97a53d1e9c2f2e6cfaef2c86cdd1bc6bb033/porespy/__init__.py#L86
with:
```python

settings.notebook = is_notebook()

def is_notebook():
    try:
        shell = get_ipython().__class__.__name__
        if shell == 'ZMQInteractiveShell':
            return True   # Jupyter notebook or qtconsole
        elif shell == 'TerminalInteractiveShell':
            return False  # Terminal running IPython
        else:
            return False  # Other type (?)
    except NameError:
        return False      # Probably standard Python interpreter
```

This works fine with Jupyter Notebooks, Spyder IPython console and plain terminals.

Reference: https://stackoverflow.com/a/39662359/3438239

**Comment by ma-sadeghi** [comment]
I just found out that getting the right `tqdm` is much easier. `tqdm` already has a function that returns the right instance:
```python
from tqdm.autonotebook import tqdm
```
Although I haven't tested it with Spyder.

Update: never mind, it doesn't work well with Spyder.

**Comment by jgostick** [comment]
Ya, I had tried that before and it didn't work.  Too bad it's not fixed yet.
