### ISSUE TITLE
AttributeError: 'pore_size_distribution' object has no attribute 'LogR'

### ISSUE THREAD

**Issue by puterd** [PMEAL/porespy#421]
Running the examples in metrics (porosimetry and thickness) I get the following error. Installed using conda and just running the example scripts. I had the same error loading my data and wanted to check if it was a general issue or not. 

AttributeError: 'pore_size_distribution' object has no attribute 'LogR'

**Comment by jgostick** [comment]
I think we may have changed it to lower case as part of our general overhaul to V2.0, which is not yet complete.  Try changing to 'logR'?

**Comment by puterd** [comment]
That worked, thanks.
