### ISSUE TITLE
TypeError: cylinders() got an unexpected keyword argument 'porosity'

### ISSUE THREAD

**Issue by puterd** [PMEAL/porespy#422]
This may be related to the development of V2.0, but just checking. I was wondering how to change the code to generate the goal porosity in the cylinders example. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-8733d7d79505> in <module>
     10 
     11 # Generate image by providing the target porosity
---> 12 im_using_porosity = ps.generators.cylinders(
     13     shape=shape,
     14     radius=radius,

TypeError: cylinders() got an unexpected keyword argument 'porosity'

**Comment by jgostick** [comment]
Can you put which version of porespy you were using?

**Comment by puterd** [comment]
Sure, the output of pip show in the notebook is:
Name: porespy
Version: 1.3.1

**Comment by jgostick** [comment]
I'm going to close this since it's an issue with different versions.  We have unit tests and examples that cover this function so I'm fairly confident that it's ok.
