### ISSUE TITLE
python version on porespy.org says 3.6+ supported but github says 3.7+

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/porespy#431]
A student of mine tried running in 3.6 and couldn't import. Probably want to update the website.
Thanks

**Comment by jgostick** [comment]
I've seen some packages have badges that list the compatible python versions...might be helpful.

**Comment by ma-sadeghi** [comment]
It seems that adding a badge is as easy as generating a link using this website: https://shields.io/category/platform-support
It only requires defining supported Python versions in `setup.py` as:
```
classifiers =
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
```
Also, it won't generate a badge until the next release (it looks up `pypi` for such info).

**Comment by ma-sadeghi** [comment]
I just added the OS and Python version description to setup.py, but it won't appear until our next release.

TODO: Before the next release, make sure to add the badge to README.
TODO: also, tidy up setup.py using https://setuptools.readthedocs.io/en/latest/userguide/package_discovery.html

**Comment by jgostick** [comment]
This is how a badge is added:

```
[![Pyversions](https://img.shields.io/pypi/pyversions/porespy.svg?style=flat-square&label=Python%20Versions)](https://pypi.python.org/pypi/porespy)
```

But it doesn't seem to work for us:

[![Pyversions](https://img.shields.io/pypi/pyversions/porespy.svg?style=flat-square&label=Python%20Versions)](https://pypi.python.org/pypi/porespy)

If you put another package it works:

[![Pyversions](https://img.shields.io/pypi/pyversions/coveralls.svg?style=flat-square&label=Python%20Versions)](https://pypi.python.org/pypi/coveralls)

**Comment by jgostick** [comment]
This has been added to the readme in the ``new_examples`` branch
