### ISSUE TITLE
Why did the two_point_correlation function doesn't work on my own images?

### ISSUE THREAD

**Issue by dingyineversad** [PMEAL/porespy#438]
My own images are tiff files,when I use your  two_point_correlation function ,it always show me the wrong results.But when I use the generators function first,then to use  two_point_correlation function ,it seem to be right.
Thank you very much for your help! @vasudevanv @arfon

**Comment by jgostick** [comment]
Please post your image file.  Nothing too large, just the minimum that will reproduce the problem.  Also, no need to mention people to get their attention, just post here is enough.  Beside, neither of the people you mentioned are porespy devs.

**Comment by dingyineversad** [comment]
> Please post your image file. Nothing too large, just the minimum that will reproduce the problem. Also, no need to mention people to get their attention, just post here is enough. Beside, neither of the people you mentioned are porespy devs.

Much to my regret，I'm a newcomer on github.
Thank you,professor,I just look up to a solution to upload my images,but failed.
But this one is similar to mine(<3mb)
[https://github.com/LukasMosser/PorousMediaGan/tree/master/data/berea/original/raw](url)

**Comment by dingyineversad** [comment]
> Please post your image file. Nothing too large, just the minimum that will reproduce the problem. Also, no need to mention people to get their attention, just post here is enough. Beside, neither of the people you mentioned are porespy devs.

Again ,thank you very much!

**Comment by jgostick** [comment]
I suspect your image is the problem, so please post an actual tiff file that you know to not work.  You can just drag and drop (see text below the comment field)

**Comment by dingyineversad** [comment]
This is my image
[rec_003jutest.zip](https://github.com/PMEAL/porespy/files/6258351/rec_003jutest.zip)

**Comment by dingyineversad** [comment]
> I suspect your image is the problem, so please post an actual tiff file that you know to not work. You can just drag and drop (see text below the comment field)
![image](https://user-images.githubusercontent.com/77733099/113579039-4f7edc80-9656-11eb-9ddc-d920b18c7911.png)

And this is my results

**Comment by dingyineversad** [comment]
> I suspect your image is the problem, so please post an actual tiff file that you know to not work. You can just drag and drop (see text below the comment field)
Thank you for your help!

**Comment by dingyineversad** [comment]
![image](https://user-images.githubusercontent.com/77733099/113664304-1a1dd180-96de-11eb-9011-c2e4a1b9b62c.png)
I solely test this by the "two_point_correlation_fft"way, and this seems no problems.
I am even more confused

**Comment by jgostick** [comment]
The image you sent me is an 8-bit integer format with 255 and 0.  I think 255 is the solid phase and 0 is the void phase.  To apply the 2-point correlation you need to do:

``` python
import porespy as ps
import imageio
import matplotlib.pyplot as plt
im = imageio.volread('rec_003jutest.tif')  # load image
im = im == 0  # Choose which voxel value is the foreground 
plt.imshow(ps.visualization.show_planes(im))  # Take a quick look
twopt = ps.metrics.two_point_correlation_fft(im)  # Run the function
plt.plot(twopt.distance, twopt.probability, 'b-o')  # Plot it
```

**Comment by dingyineversad** [comment]
> ```python
> import porespy as ps
> import imageio
> import matplotlib.pyplot as plt
> ```

![image](https://user-images.githubusercontent.com/77733099/113726134-8de3cc80-9726-11eb-8be4-8b53de0a8490.png)
Thank you very much,but I have no idea what went wrong.This is my result and seems not exactly right.

**Comment by dingyineversad** [comment]
> The image you sent me is an 8-bit integer format with 255 and 0. I think 255 is the solid phase and 0 is the void phase. To apply the 2-point correlation you need to do:
> 
> ```python
> import porespy as ps
> import imageio
> import matplotlib.pyplot as plt
> im = imageio.volread('rec_003jutest.tif')  # load image
> im = im == 0  # Choose which voxel value is the foreground 
> plt.imshow(ps.visualization.show_planes(im))  # Take a quick look
> twopt = ps.metrics.two_point_correlation_fft(im)  # Run the function
> plt.plot(twopt.distance, twopt.probability, 'b-o')  # Plot it
> ```

And this is the result accroding to  the documentation in porespy (after use the picture convert code)
![image](https://user-images.githubusercontent.com/77733099/113726682-05b1f700-9727-11eb-9126-5bc14e856205.png)

**Comment by jgostick** [comment]
why is this not right?  It's only doing 4 distances because your image is very small.  After we do the fourier transform we need to extract the results at different radial positions in the fourier domain, so we draw circles of radii [1, 2, 3, etc].  Your image is so small that it only fits 4 circles then stops.

**Comment by dingyineversad** [comment]
Oh, I see...Thank you very much

**Comment by dingyineversad** [comment]
![image](https://user-images.githubusercontent.com/77733099/114303259-d1ac4c80-9aff-11eb-8bda-aae1679c061a.png)
Sorry to interrupt again, could you please tell me how to get the lineal_path_distribution result by porespy?
Thank you very much,professor

**Comment by jgostick** [comment]
Could you re-ask this question under the [Discussions tab](https://github.com/PMEAL/porespy/discussions)?  It's a good one to have in the archive of answered questions.

**Comment by dingyineversad** [comment]
OK
