### ISSUE TITLE
Parallelize unit tests

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#466]
Similar to PR #463, but for unit tests. Not urgent though, as our unit tests are still manageable.

**Comment by jgostick** [comment]
Just out of curiosity, what would this entail? I'm guessing we have to break the tests up into more files, so there would be something wiggle room in how the tests were divided up?

**Comment by ma-sadeghi** [comment]
I think we'll be fine without breakup them up. `pytest` smartly handles that (maybe in the backend it creates a new test class for each batch of tests and adds the `setup_class` and `teardown_class` methods to it). I just split `test_filters.py` into 4 groups and they all ran fine.

The issue with IPython notebooks is that they don't have a setup/teardown phase, and even if they did, some cells might still/probably will depend on some other intermediate cells. So, the only way to ensure that a notebook runs without error is to run all cells consecutively.

**Comment by ma-sadeghi** [comment]
Similar to PMEAL/OpenPNM/issues/2099, so let's close this one too.
