### ISSUE TITLE
Determine overlap width in snow_partitioning_parallel heuristically 

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#482]
In my experience, `snow_partitioning_parallel` is not very robust. I often times get the error that the overlap width is incompatible. Usually, when I manually pass it as 10-20% of the chunk width, it gets fixed. Can we figure out some sort of heuristics that can be used to automatically determine overlap width unless specified by the user so the method almost always just works?

@Zohaib-Atiq @jgostick

**Comment by jgostick** [comment]
It should probably be ``overlap=None`` which will use the maximum of the distance transform, or ``overlap=10`` will apply 10 in all directions and ``overlap=[40, 30, 10]`` will apply the given amounts in each direction.  We should also offer a function that can find the overlaps for you.

**Comment by jgostick** [comment]
I have turned ``overlap`` into a ``scalar`` or ``None`` option. If ``None``, the it get calculated by a few function called ``estimate_overlap``, which uses ``mode='dt'`` by default.  If you want to get a better guess of this you can call the function yourself.  Eventually, we'll want this to optionally have different overlaps in each direction, for instance.
