### ISSUE TITLE
crop argument in snow_partitioning_parallel might be too much control/fine tuning

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#485]
I think the `crop` argument is giving too much control and hence unnecessarily polluting the arg list. In my opinion, the method should always work regardless of the value of `divs`.

**Comment by jgostick** [comment]
yes, I agree with that.  trimming 1 or 2 voxels is probably permissible given that this function is literally designed to work with massive images.

**Comment by ma-sadeghi** [comment]
Would it not work if the chunks are not all equal in size? (so that there's no need to crop in the first place)
For instance, suppose the image is 10-wide and we request `divs=3`, in which case the chunks will be 3, 3, and 4-wide, respectively.

**Comment by jgostick** [comment]
So, no, it does not work with uneven or at least unsimilar chunk sizes:

```
ValueError: The overlapping depth 30 is larger than your
smallest chunk size 1. Rechunk your array
with a larger chunk size or a chunk size that
more evenly divides the shape of your array.
```

**Comment by jgostick** [comment]
I have updated the code to always crop if necessary, then it adjusts the input images to also be cropped.  Throws a warning obviously.
