### ISSUE TITLE
Show in Local thickness in 3D 

### ISSUE THREAD

**Issue by josephinoo** [PMEAL/porespy#490]
Hello, could you help me, how to graph the Local thickness in 3D, I read a paper of your property, that they used that method, I would like to be able to graph with the image shown below: 
![Captura de Pantalla 2021-04-14 a la(s) 23 43 34](https://user-images.githubusercontent.com/46098690/114815362-a9308680-9d7b-11eb-8e70-cdd6ca9cb094.png)

**Comment by jgostick** [comment]
We used paraview for that.  You can save images as tiffs, and opening them directly in paraview. You then use a 'threshold' to remove parts you don't want.  also, be sure to enable ray tracing to get the photorealistic shadows ;-)

**Comment by josephinoo** [comment]
Could you help me with an example to guide me, I have created the tiff with tifffile, but it only shows a slice in paraview 
<img width="1264" alt="Captura de Pantalla 2021-04-15 a la(s) 00 28 29" src="https://user-images.githubusercontent.com/46098690/114818512-8608d580-9d81-11eb-8a68-f1fb88fd34e4.png">

**Comment by jgostick** [comment]
You probably only saved 1 slice.  Use the imageio package:  ``imageio.volsave('filename.tif', np.array(tif_array, dtype=np.int32)``
