### ISSUE TITLE
Tidy up new examples

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#503]
The examples are almost ready to be merge, but need few finishing touches.

- [ ] Ensure pep8 rules are followed (i.e. r=8 instead of r = 8).
- [ ] Change title of first sub-section to "Generate Image for Testing" instead of "Create image and variables"
- [ ] Sprinkle a few more sentences throughout explaining each step
- [ ] Remove comments from code blocks and convert to explanatory sentences if possible
- [ ] Remove the few lingering attempts to print the docstring at the top
- [ ] Set ``ps.settings.loglevel = 50`` to avoid warnings
- [ ] Ensure ps.visualization.set_mpl_style() is called at the top of each
- [ ] Set np.random.seed(x) at the to of each file (where x should be a found that gives a good looking result)
- [ ] Set figsize=[N*4, 4] were N is the number of panels in the image
- [ ] Ensure semicolons are placed at the end of each cell to suppress matplotlib output

**Comment by Ni2M** [comment]
an additional note: I noticed sometimes a function is used to generate/prepare an image before working on the main function. For example apply_chords is used to generate an image for testing count_chords. So the first function is just to prepare the image and there's no need to write all its default input arguments (unless the default vlaues are changed)

like: ps.filters.apply_chords(im, spacing=1, axis=0, trim_edges=True, label=False)
should be:
ps.filters.apply_chords(im)

**Comment by Ni2M** [comment]
after some thoughts, I think/propose including default values for functions might not be necessary, as the user can see the default values in the docstring printed help. Also we want to show the user that with having only image you can call this function and get a result.
Then for value other than default we have additional cells with example to show that you can change the default values based on the application (these cells are already available in howtos)
