### ISSUE TITLE
metrics.phase_fractions requires phase labels to contain no gaps

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#507]
# Issue with gaps in the labels
## Current output
```
q
Out[23]: array([ 0,  0,  1,  1, 12,  1, 12, 12, 12, 12])

ps.metrics.phase_fraction(q)
Out[24]: array([0.2, 0.3, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5])
```

## Expected
```
q
Out[23]: array([ 0,  0,  1,  1, 12,  1, 12, 12, 12, 12])

ps.metrics.phase_fraction(q)
Out[24]: array([0.2, 0.3, 0.5])
```

## Or even better
```
q
Out[38]: array([ 0,  0,  1,  1, 12,  1, 12, 12, 12, 12])

ps.metrics.phase_fraction(q)
Out[44]: {0: 0.2, 1: 0.3, 12: 0.5}
```

# Issue that the method doesn't work with floats
## Current output
```
x
Out[15]: array([ 0.5,  0.5,  1.5,  1.5, 12. ,  1.5, 12. , 12. , 12. , 12. ])

import porespy as ps

ps.metrics.phase_fraction(x)
Traceback (most recent call last):

  File "<ipython-input-17-f62def6fb91a>", line 1, in <module>
    ps.metrics.phase_fraction(x)

  File "c:\users\amin\code\porespy\porespy\metrics\__funcs__.py", line 812, in phase_fraction
    raise Exception('Image must contain integer values for each phase')

Exception: Image must contain integer values for each phase
```
## Expected
```
x
Out[46]: array([ 0.5,  0.5,  1.5,  1.5, 12. ,  1.5, 12. , 12. , 12. , 12. ])

ps.metrics.phase_fraction(x)
Out[47]: {0.5: 0.2, 1.5: 0.3, 12.0: 0.5}
```

**Comment by jgostick** [comment]
I'm not sure it should work with floats.  It should be a 'labelled' image, and the labels should be integers. I suppose it wouldn't "hurt" to work with floats.  It'd be simple enough.

**Comment by ma-sadeghi** [comment]
Ya, I see your point. It's just that sometimes the labeled image ends up being `float`, for instance by `im = phase1*1.0 + phase2*2.0` (like in the notebook that we generate the CL image). I thought maybe this method shouldn't complain in those special cases.

**Comment by jgostick** [comment]
I meant to say "wouldn't hurt" above.  The function essentially does a bincount on the image, so floats get dumped into bins anyway.  The 'bins' could be found from ``np.linspace(1, im.max(), nbins)``.
