### ISSUE TITLE
align_image_with_openpnm might no longer be needed

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#523]
See https://github.com/PMEAL/porespy/discussions/514#discussioncomment-649533

**Comment by ma-sadeghi** [comment]
@jgostick should we remove it?

**Comment by jgostick** [comment]
This has always been a mystery to me.  Did we do something to change things, or did it automagically fix itself?

**Comment by ma-sadeghi** [comment]
I'm not sure, but maybe something changed in Paraview.

**Comment by jgostick** [comment]
This is still needed when loading a tiff image to paraview.  When loading other formats perhaps not, but for tiff yes its needed.
