### ISSUE TITLE
snow2's boundary_width is a bit difficult to work with

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#527]
For instance, passing `[0, 3, 0]` breaks the code. However, one might expect that it should only pad the y-axis by 3 voxels. 

I think we should make it more intuitive to work with.

On another note, do we really need to expose the "number of padded voxels" in snow2's args? One might use 1 voxel, which IIRC, breaks the marching cubes algorithm.

**Comment by jgostick** [comment]
I works exactly the same as numpy.pad.  I also thought that [0, 3, 0] would be apply to each axis, like [[0, 0], [3, 3], [0, 0]], but the problem is this is impossible to interpret for arbitrary dimension, so pad works like [before, after] which applies to ALL axes, regardless of dimension.

**Comment by ma-sadeghi** [comment]
Ya, right. I only opened up this issue since Saeid was a bit confused by the new convention. Most of it, I hope, is because it takes time to get used to the new convention, but I was wondering if there might be a more intuitive way. Anyway, I know you've put lots of thought into this, so this is probably our best shot.

**Comment by ma-sadeghi** [comment]
Maybe to make it a bit more self-descriptive, we could change the default value to `[[3, 3], [3, 3], [3, 3]]` instead of `3`? Not sure if that's a good idea though.

**Comment by jgostick** [comment]
I think it can be made a bit more flexible, but we can also include a mention of the np.pad function in any error messages.  Your proposal only works for 3d images, which is why it's a scalar.

**Comment by jgostick** [comment]
I think this is just life.  If we want truly adjustable boundary regions then it needs to be this way.
