### ISSUE TITLE
Running the examples in Networks (SNOW network extraction) I get the following error. AttributeError: module 'porespy.networks' has no attribute 'snow2'

### ISSUE THREAD

**Issue by haugust9377** [PMEAL/porespy#535]

**Comment by jgostick** [comment]
We are in the process of updating the code to version 2.  The examples are all based on version 2 but we have not yet pushed v2 to pypi.  I plan to finish it this week.  Sorry about that.  You can get V2 by cloning the github repo, checking out the dev branch and installing it from source using ``pip install -e .`` from the directory containing the code.  You'll want to create a virtual env first probably so you don't overwrite your other installation.
