### ISSUE TITLE
Issue with snow_basic tutorial

### ISSUE THREAD

**Issue by rpshi** [PMEAL/porespy#538]
Hi there,

Thanks for the great tool.

I was trying to run snow_basic.ipynb and had some issues.

Please see below:
```python
snow_output = ps.networks.snow2(im, voxel_size=1)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-1c7f5acaff58> in <module>
----> 1 snow_output = ps.networks.snow2(im, voxel_size=1)

AttributeError: module 'porespy.networks' has no attribute 'snow2'
```

I changed snow2 to snow, it worked.

But another issue came up:
```python
pn.update(snow_output.network)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-8d5c0a07ab1d> in <module>
pn.update(snow_output.network)

AttributeError: '_net_dict' object has no attribute 'network'
```

Could you please help to take a look when you find time?

I just updated `porespy` to the most recent version by using the command below,

```bash
conda install -c conda-forge porespy
```
Thanks,

Rongpei

**Comment by rpshi** [comment]
never mind please close the issue

**Comment by rpshi** [comment]
i used pip list to check porespy                            1.3.1 has been installed

**Comment by rpshi** [comment]
The options i have are:

 ps.networks.snow 
                     snow_dual 
                     snow_n

**Comment by jgostick** [comment]
Yes, we are in the midst of version bumps in both porespy and openpnm.  Sorry for the inconvenience, and I"m glad you got it sorted.

``snow_2`` is on porespy version 2 and it unifies all the work we've done in the past few years, but it's not officially ready for release yet, so is not on pip.  Give us a week or so.
