### ISSUE TITLE
When will PoreSpy 2.0 be ready?

### ISSUE THREAD

**Issue by rpshi** [PMEAL/porespy#539]
looking forward to trying the porespy 2.0 :)

**Comment by ma-sadeghi** [comment]
PoreSpy is pretty much (99%) done, the only reason we are lingering is that we need to make sure PoreSpy 2.0 is compatible with the future changes we want to make to OpenPNM (our other package for doing pore network simulations). OpenPNM 3.0 is on the horizon, and we're trying to future-proof PoreSpy 2.0. 

Anyway, hopefully in a few weeks (or maybe sooner!).

**Comment by rpshi** [comment]
thanks for the update!
