### ISSUE TITLE
Add type annotation to the code

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#56]
Tom and I are working on making a PoreSpy plugin for Dragonfly and data types are a bit difficult to deal with in Qt. It would help a lot if methods were type-annotated. Native type annotation is supported in Python 3.5+, so that should not be a problem. Here's how they work:

```
import typing
from typing import get_type_hints


def f(x: int, y:float):
    return x + y

>>> get_type_hints(f)
{'x': int, 'y': float}
```

The good thing is that type annotation doesn't break any code as it's not enforced and is only used as a hint.

**Comment by jgostick** [comment]
go for it!  But we're in the middle reorganing for the JOSS thing, so let me merge the JOSS_reorg branch into dev, then you can branch from that

**Comment by TomTranter** [comment]
@ma-sadeghi is this finished?

**Comment by ma-sadeghi** [comment]
@TomTranter, I guess we have what we need.

**Comment by jgostick** [comment]
This is done in the generators module
