### ISSUE TITLE
Why does snow2 expect `phases` indices to be contiguous?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#573]
Why not make it more general, so that `phases` can contain any arbitrary sequence of labels, e.g., `[1, 5, 10, 12]`.

**Comment by jgostick** [comment]
This is an easy fix...change line 129 from:

```for i in range(phases.max()):```

to 

```python
vals =  np.unique(phases)
vals = vals[vals > 0]
for i in vals:
```

**Comment by jgostick** [comment]
Interestingly, ``snow_partitioning_n`` already accepted this.  It's addressedin PR #659

**Comment by jgostick** [comment]
I have halved the size of the 3D image, so should be 8x faster?

**Comment by jwdeltaT** [comment]
Thank you. Your email is received and will be handled as soon as possible.
