### ISSUE TITLE
Issues while importing

### ISSUE THREAD

**Issue by GabrielFNBR** [PMEAL/porespy#589]
Hi Guys!
I'm having a issue while trying to import the porespy.

I've installed with

`$ conda install -c conda-forge porespy`

And the error I got whenever I try to import is

import porespy as ps

cannot import name 'match_histograms' from 'skimage.exposure' (/Users/gabrielferes/anaconda3/lib/python3.7/site-packages/skimage/exposure/__init__.py)

Any idea?

**Comment by ma-sadeghi** [comment]
Probably, you are using an old version of `skimage`. Try updating it:
```bash
conda update scikit-image
```
