### ISSUE TITLE
pore_size_distribution function does not return R or logR

### ISSUE THREAD

**Issue by jihyeoh5** [PMEAL/porespy#591]
```python
AttributeError: 'Results' object has no attribute 'R'
```
Users have a workaround available to find radius values from 'bin_centers'

**Comment by ma-sadeghi** [comment]
@jihyeoh5 Are you interested in fixing this in a pull request? Thanks!

**Comment by jihyeoh5** [comment]
Hi Amin,

Sure, I'm interested to try!

Regards,
Jihye.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jgostick** [comment]
The R vs logR depends on whether you set the ``log`` flag to ``True``.
