### ISSUE TITLE
Possibility to combine pore networks generated by porespy?

### ISSUE THREAD

**Issue by JoHommel** [PMEAL/porespy#594]
I have trouble to extract a single PN from my µCT-data of column experiments, likely due to the size of the data set and memory limitations, but I would like to have a single PN for each experiment. I searched the porespy documentation, but I could not find any function that looks as if it would do the job. 
In principal, it should be simply searching for pore bodies with identical/similar coordinates, merging them, and checking and updating the pore throats, if necessary. 
Doing this by hand seems tedious and prone to errors. I am grateful for any hints or insights into this issue.

**Comment by jgostick** [comment]
I am not sure I understand your problem.  I assume the pore structure is not changing, hence you expect a single PNM to fit all the images.  So why can't you just extract the PNM from the first experiment and use that for all the others?
