### ISSUE TITLE
delete boundary_pores branch?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#61]
@Zohaib-Atiq has implemented a way to add boundary regions to the image so that the extraction algorithms create boundary pores.  @TomTranter has a branch open that seems to do this also....I think you two both worked together on this, so I just want to confirm that the code on @TomTranter's branch is not needed and it can be deleted.

**Comment by TomTranter** [comment]
I haven't worked on that branch for a while but I sent Zohaib the main code I had working for the boundary pores months ago. I assume what he has is better and more up to date so I'd say just delete that branch and if I need to anything else I will cross that bridge when it comes

**Comment by Zohaib-Atiq** [comment]
The difference I see between add boundary regions and tom boundary function is 
A: Removing connections between boundary cells
B: Specify at which face boundary cells are needed. 
C: Boundary cells are 3 voxel wide
From last three months, I haven't used @TomTranter boundary function also so not sure about if he has made any other changes.

**Comment by TomTranter** [comment]
Why 3 voxels? Could this be an argument... In principle I have no problem with it but not sure why it's necessary. Specifying faces fine. I think I do remove interconnections but if I don't then I agree I should

**Comment by Zohaib-Atiq** [comment]
> Why 3 voxels?

This was added because the marching cube algorithm was not able to calculate the surface area on one voxel wide boundary cells. So 3 voxels wide boundary cells were used.
> Could this be an argument

Yes, it can be added as an argument as well but I didn't observe its need in snow_dual until now.
