### ISSUE TITLE
Figure out why two of metrics tests are failing on Github

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#612]
I've tagged the following tests so `pytest` skips them since they fail on github, but pass locally. Need to investigate.

```python
MetricsTest.test_mesh_surface_area
MetricsTest.test_region_interface_areas
```

**Comment by jamesobutler** [comment]
@ma-sadeghi This appears to be a duplicate issue of #607.

**Comment by ma-sadeghi** [comment]
@jamesobutler Oops! My bad! Nice catch, thanks!
