### ISSUE TITLE
Edges of local_thickness show an artifact

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#64]
A 1-voxel thick artifact is appearing at the edges of the local thickness result

**Comment by mdrkok** [comment]
Is there a way to fix this or should we implement a 'remove_ones' option in the psd function?

**Comment by jgostick** [comment]
The problem is that the edges is 1 voxel thick, but the values are not 1's...if I recall correctly.

**Comment by jgostick** [comment]
There are two things going on....the inscribed spheres do not make it to the edge, plus there seems to be some 1's in there somewhere.  When getting the local thickness from the porosimetry function with mode='dt', these problems are gone.

**Comment by mdrkok** [comment]
i think i've got this mostly sorted, the difference is a strel from disk(rad) is slightly different at the edges than the structuring element implied by spim.distance_transform_edt(something)<rad.

I'm still getting some phantom differences of 1 showing up so its not done but I'm pretty sure that was the problem, the rest is probably the weird way I jerry rigged it all together

**Comment by jgostick** [comment]
Fixed in #109
