### ISSUE TITLE
Do we really need the badges? 

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#646]
Does anyone care if our tests and examples on dev are actually passing?  The DOI is listed in the readme and on the new 'how to cite' section in the right sidebar.  The version and python version are also pretty pointless, and can be found pypi.

**Comment by ma-sadeghi** [comment]
I agree on the version and supported Python versions. But, I think the DOI gives the occasional user a quick impression that this software can/should be cited. Regarding the tests/examples, I think they're useful, but for the most part for our own sake. The alternative would be to go to the Actions page, filter by branch, and look at the latest test and see if it's passing.
