### ISSUE TITLE
The pad_width argument does not work as expected in 2D

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#651]
In the ``add_boundary_regions`` function we have added the ability to specify that [10, 5, 0] means add 10 to the beginning and end of the first axis, 5 to the second, and 0 to the third.  In 2D however, [10, 0] adds 10 to the beginning of the first and second axis, and 0 to the ends.

**Comment by jgostick** [comment]
I'm not sure why I got the above error, this is no longer happening?  Maybe I was on an old branch and didn't realize it?

I do notice that there is not test specfically for this so I have updated it on the snow maintenance branch

**Comment by ma-sadeghi** [comment]
I just tested and it seems to work.

```python
import porespy as ps

pw = [10, 0]

ps.networks._snow2._parse_pad_width(pw, shape=[100, 100])
Out[18]: 
array([[10, 10],
       [ 0,  0]])
```
