### ISSUE TITLE
Cylindrical plug generator does not work for 2D shapes

### ISSUE THREAD

**Issue by NicholasFrancken** [PMEAL/porespy#652]
Using porespy.generators.cylindrical_plug for 2D shapes results in an error:  ```UnboundLocalError: local variable 'axes' referenced before assignment.```

Looking at the source code it appears that 'axes' is defined only for 3D shapes. I believe an easy fix is putting 'axes' before the 3D/2D conditionals.

**Comment by jgostick** [comment]
Thanks for letting us know.  I have fixed in our on-going PR called "tidy_docs".  In the meantime, you can always make a 3D image with a shaple like [100, 100, 1], then apply ``np.squeeze`` to the result to remove the last 'singleton' dimension.
