### ISSUE TITLE
Better init for steady state multiphase flow LBM sims

### ISSUE THREAD

**Issue by je-santos** [PMEAL/porespy#653]
Dear PoreSpies,

Would someone be interested in helping us with setting up better initial conditions for our multiphase LBM solver?

https://github.com/je-santos/MPLBM-UT/issues/60

We just finished our  transition to python and we would like to be friends :)

**Comment by jgostick** [comment]
This conversation has been continued on Javier's repo, so I'm going to close this issue.

**Comment by wwx2277** [comment]
Dear santos,

i have tried to run your stable_state_flow,and i have a problem that if shan-chen modle can play in gas-water two phase flow?
