### ISSUE TITLE
`networks.maximal_ball_wrapper` produces no output

### ISSUE THREAD

**Issue by minzhangut** [PMEAL/porespy#686]
I am able to run `ps.networks.maximal_ball_wrapper(im, "test", "./pnextract.exe", voxel_size=resolution)`, but I did not get any output files?

**Comment by ma-sadeghi** [comment]
Hey @minzhangut, thanks for reporting. I don't currently have Windows to reproduce the bug, and the wrapper only works on Windows. If you're just looking for a network extraction method, you're probably better off using `snow2`, but if you particularly need the maximal ball extraction, you'd have to wait as we're currently working on releasing OpenPNM v3, and it's taking almost all of our time.

**Comment by ma-sadeghi** [comment]
@minzhangut In the meantime, you could look into `test_max_ball` under `test/unit/test_network_extraction.py`. The test ensures that the method produces the expected output, and they seem to pass on Github. So, maybe you could start by running `test_network_extraction.py` and see if you get any outputs (you need to comment those lines that delete the generated files after they get created).

**Comment by jgostick** [comment]
We are going to remove this function from V3 since supporting it became more trouble than we expected.
