### ISSUE TITLE
`imageio.volwrite` has been deprecated and no longer works with recent tifffile

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#690]
These tests/notebooks are currently failing and need to be updated asap:

- `examples/visualization/tutorials/visualizing_tif_in_paraveiw.ipynb`
- `examples/networks/tutorials/snow_advanced.ipynb`
- `test\unit\test_network_extraction.py`

`imageio`'s docs has a [section](https://imageio.readthedocs.io/en/stable/reference/userapi.html?highlight=volwrite#writing-images) on how to fix it.

**Comment by jgostick** [comment]
closed by PR #811
