### ISSUE TITLE
`tqdm` seems to have changed something in their backend

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#709]
See Discussion #707

**Comment by ma-sadeghi** [comment]
It might be good idea to switch to using `rich` for logging/progress bars/etc. I've already experimented logging with `rich`, and the transition should be relatively smooth, see [here](https://github.com/PMEAL/OpenPNM/discussions/2519). I don't think migrating the progress bars should be any more difficult, see [here](https://rich.readthedocs.io/en/stable/progress.html).

**Comment by jgostick** [comment]
These seem to be working well again.
