### ISSUE TITLE
`_estimate_overlap` should accept dt argument for speed

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/porespy#760]
Please see the [code](https://github.com/PMEAL/porespy/blob/9fc5b51b007ef036a2fbeee843ef8b29d7c48144/porespy/filters/_snows.py#L583)

Often we already have the distance transform of the image. Why should we recalculate when estimating the amount of overlap? Why not just give it the dt of the image?

**Comment by jgostick** [comment]
This seems like a duplicate of #736
