### ISSUE TITLE
two_point_func and chord_length in porespy are not available for user's image（the image format is tiff）

### ISSUE THREAD

**Issue by likeduck** [PMEAL/porespy#767]
Dear prof，
in two_point_func using my image resulted 'real two point' like this:
![Figure_1](https://user-images.githubusercontent.com/117707506/204003629-0592da7f-090c-40dd-a2e5-beee79de59bb.png)
my code are these:
![捕获](https://user-images.githubusercontent.com/117707506/204003889-04395b45-ace5-468e-bdd0-af1cb0c2cffa.PNG)
it puzzled me and i have no idea to solve it while using my own image
in chord_length, my code like this:
![捕获 PNG1](https://user-images.githubusercontent.com/117707506/204004268-d9da427d-8067-4310-9cdd-0ab9564b4d5c.PNG)
run it i get a null white background without image and chord，how do I solve that?

**Comment by jgostick** [comment]
I think that you're not using the ``imageio`` package properly. ``imread`` only reads in 2D images.  The function you want used to be called ``mimread`` where the first "m" stood for "multi".  In more recent versions they have the much more sensibly named ``volread`` which reads in a 3D volumetric image like your tiff is, presumably.  

In addition to that, you should also check that your image is boolean and not greyscale.  This means 2 things:  Firstly if you're working with images directly from the xray machine you need to segment the image into True (void) and False (solid).  Secondly, if you've done the first part, then the tif image is probably stored as integers, so you'll need to do a boolean mask to convert to True/False, like ``im = im >= 255`` or whatever.  You can sort this out by doing ``ps.imshow(im)`` on your image, which is a custom function in porespy that shows you a slice of a 3D image.   Is it greyscale or boolean?  When you hover over the image matplotlib reports the pixel value under the curor, is it 0 and 255?  Etc.  You can also print it with ``print(im)`` and do ``print(im.shape)`` to learn the info you need.
