### ISSUE TITLE
Need generators to produce images with more than 2 phases

### ISSUE THREAD

**Issue by Zohaib-Atiq** [PMEAL/porespy#78]
Currently, we have generators that generate boolean images. We can extract at maximum two phases from them. Can we have generators with more than two phases? It will help to extract more phases using snow_n.

**Comment by jgostick** [comment]
I think this is best handled by examples rather than dedicated functions.  For instance, one can use RSA to insert spheres, and each output a different number, or you could do blobs, then add spheres with RSA.
