### ISSUE TITLE
A function that gives phase fraction of all phases in image 

### ISSUE THREAD

**Issue by Zohaib-Atiq** [PMEAL/porespy#79]
This will be quite useful while extracting n phases from the image. It will tell the fraction of all phases in one go.

**Comment by mdrkok** [comment]
Do you mean like np.unique?

**Comment by jgostick** [comment]
like porosity, but for all phases

**Comment by Zohaib-Atiq** [comment]
@jgostick Yes.
For example the output would be something like
______________________
phase         fraction
______________________
phase 1---->0.3
phase 2---->0.4
phase 3---->0.3
______________________
Total ------>1.0

Total will 1.0 for sure but if the image has float values this will let us know that something is wrong.

**Comment by mdrkok** [comment]
ok cool, np.unique(im, return_counts=True) will return two tupples, one with each unique value in the image (so each phase) and the second the counts of each, so making a function return the phase fraction for each phase is straightforward, ill add something

**Comment by Zohaib-Atiq** [comment]
@mdrkok I found np.unique to be very slow as compared to just masking the image with phase label and counting Trues. Also if a user inputted an RGB image or any image that has float values in it by mistake np.unique will go crazy and calculates unnecessary phase fraction values. For example phase 0.32453465---->0.0001 which we don't need for sure :). I think function arg can have phases labels input which user can provide and by default it is set to 1 value for phase 1 which is equivalent to porosity function? Just throwing an idea :)

**Comment by mdrkok** [comment]
My experience is that tomography always comes in an rgb triple so im.shape = [x,y,z,3], so when its loaded in you need to use imread(im, as_grey=True) to make it 3 dimensional, meaning all the values will be float values, so at the very least you'll need np.unique to determine what values you have, then you might as well count then. 
So maybe were just approaching it from two perspectives, I agree its not the fastest if you have a well defined Int image but I also don't think the average user will have an Int image, but probably an rgb

**Comment by Zohaib-Atiq** [comment]
ok sounds good.

**Comment by jgostick** [comment]
look into ``sp.stats.itemfreq``

**Comment by jgostick** [comment]
create a new function, perhaps called ``phase_fraction`` that counts the number of occurrences of non-zeros, and returning a dict or list, like [0, 444, 6948, 333], though should probably be normalized, like [0, 0.3, 0.55, 0.22, ...]

**Comment by jgostick** [comment]
added in PR #121
