### ISSUE TITLE
Messed Up PR

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/porespy#8]
Hey @jgostick ,

I forgot to make my changes on a new branch, but created a new one when pushing from source tree and it seemed to update master too. I reversed the commit to master but now the PR from the new branch doesn't seem to work - it wants to reverse the commit for some reason.
Hopefully you can sort out my mess :-)

Guess we could just reverse the reversal and delete the branch

**Comment by jgostick** [comment]
fixed
