### ISSUE TITLE
snow2 interested in only one phase

### ISSUE THREAD

**Issue by thsmit** [PMEAL/porespy#848]
Hi all,

I am trying to get snow2 to work. I am getting an error:
Exception: The selected overlapping thickness is not suitable for input image. Change overlapping criteria or manually input value.

Input is a 3D im, with three phases, although i am only interested in the solid phase. Command:
net = ps.networks.snow2(phases=im, phase_alias={0: 'inactive', 1: 'solid', 2: 'void'}, boundary_width=5)

Any suggestions for a solution?

**Comment by jgostick** [comment]
Firstly, set the phases that you are not interested to 0, so do `im = im == <phase of interest>`.  The error you are getting I "think" comes from the parallelization, so maybe set ``parallelization=None`` to see if it stops.

**Comment by thsmit** [comment]
Thanks! And it was the parallelization so it is solved now :)

**Comment by jgostick** [comment]
The parallelization may be suffering from dependency rot, since it's been 2-3 years since we've work on it.  I'll make a mental note to keep an eye on that in future.
