### ISSUE TITLE
Export to COMSOL

### ISSUE THREAD

**Issue by kunal0kumar0sinha** [PMEAL/porespy#868]
Please tell me how to export 2D overlapping blob images to COMSOL format. 

I also tried to export this to .tif format using following command, but got an error. 

import imageio
​
snow = ps.filters.snow_partitioning(im)
regions = snow.regions
imageio.volsave("regions.tif", np.array(regions.astype("uint8")))

ValueError: Image must be 3D, or 4D if each voxel is a tuple.

![image](https://github.com/PMEAL/porespy/assets/123363487/39aea6cd-b26b-4d98-9e56-c8e60bc0d2dd)

**Comment by jgostick** [comment]
Your best bet is to take the numpy array that is the image, and use one of the other tools on the internet.  As @ma-sadeghi points out in #869, this function is more trouble than it's worth.
