### ISSUE TITLE
SNOW network extraction

### ISSUE THREAD

**Issue by morendong** [PMEAL/porespy#879]
I followed the example of **snow_basic.ipynb**, whiel in the following part:
"The snow function returns an object that has a network attribute. This is a dictionary that is suitable for loading into OpenPNM. The best way to get this into OpenPNM is to use the PoreSpy IO class. This splits the data into a network and a geometry:
pn = op.io.network_from_porespy(snow_output.network)"
The PoreSpy can not convert to OpenPNM, and I try other ways which also did not work.
Can you give me some suggestions? Thanks!

**Comment by jgostick** [comment]
Can you be more specific about the problem you're getting?  This line should work: "pn = op.io.network_from_porespy(snow_output.network)".  We use it all the time.  Maybe you have out of date versions on your pc?

**Comment by morendong** [comment]
My OpenPNM version is 3.2.0.
and I use "pn = op.io.PoreSpy.import_data(snow_output.network)", which could work.
But the results only contain "net" and "geo" in pn.

**Comment by morendong** [comment]
That is ok!
It is the problem in work environment.

**Comment by jgostick** [comment]
Something seems a bit off with your result because OpenPNM 3.2 no longer splits data up between network and geometries, it just dumps it all into the network.  So if you're seeing net and geo, then you must be using an older version of OpenPNM.
