### ISSUE TITLE
How to get grain size distribution through the image generated from PoreSpy

### ISSUE THREAD

**Issue by morendong** [PMEAL/porespy#882]
I have generated a porous media cube through PoreSpy.
and the pore size distribution can be obtained, it is very nice!
But, I want to get information on soil texture, such as grain size distribution.
Can you give me some advice on how to deal with it?

**Comment by jgostick** [comment]
Firstly, this is a Discussion, not an issue/bug report, so I will move it there.  Secondly, this is an easy answer...just invert the image, like `solids = ~voids`, or `solids = voids == 0)`
