### ISSUE TITLE
Redundant `edges` argument in `pseudo_gravity_packing`

### ISSUE THREAD

**Issue by heinsimon** [PMEAL/porespy#916]
The [documentation](https://porespy.org/modules/generated/generated/porespy.generators.pseudo_gravity_packing.html#porespy.generators.pseudo_gravity_packing) and the [function header](https://porespy.org/_modules/porespy/generators/_pseudo_packings.html#pseudo_gravity_packing) include the argument 'edges'. Changing this argument from default value does not change anything in the output.

Checking the source code revealed: it is not used within the function itself.

I would expect either an error/warning when changing the argument from default value or not having this argument at all.

**Comment by jgostick** [comment]
That function is in need of some fixes.  I think there are already some bug reports on the issue tracker so I'll affect this to the list.
