### ISSUE TITLE
fractal_noise porositiy as an argument

### ISSUE THREAD

**Issue by amirDahari1** [PMEAL/porespy#963]
In (almost?) all other generators, porosity is a given argument when calling the generator function, except fractal_noise. Why is that? Can it be added as an argument?

Thanks!
Amir

**Comment by jgostick** [comment]
The reason, IIRC, is that the noise in the fractal images is not generated normally so it's not possible to threshold to the exact value without trial and error.  However, just today there was a very nice PR made to the project (thank you!) that fixes an issue for the blobs generator, and I suspect it will also apply here too. We should see if this new 'any_to_uniform' function can work on noise as well.

**Comment by amirDahari1** [comment]
Yes I see it makes sense (I'm happy to contribute :)), now that any noise distribution can be transformed to uniform I've added a porosity argument to `fractal_noise` in the same PR.

**Comment by jgostick** [comment]
Your contributions are greatly appreciated.
