### ISSUE TITLE
Should funcs return a normal dict instead of a "results" object?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#971]
The results object has attributes attached like `result.im_blah`, while a `dict` would be `result['im_blah']`.  The dict is a bit more 'normal' but lacks other custom functionality, like printability.

**Comment by ma-sadeghi** [comment]
Another "normal" option would be dataclasses

**Comment by jgostick** [comment]
We have decided to keep the Results object as the main return container, since they have a "clean" name space, meaning the autocomplete menu only contains the actual attributes, no additional cruft like methods and other meta info.  For instance, named tuples have `count` and `index` by default and dicts have lots of methods like `keys` etc.  The clean namespace is better to just show only what is relevant.

**Comment by JorgeESantos** [comment]
Greetings and if I may,

It would be useful and practical for the Results object to contain a method that would allow the extraction/conversion to a common dictionary. Something like:

```
psd = psd.__dict__
psd = {key: value for key, value in psd.items() if not key.startswith('_')}
```

psd is a Result object from the pore_size_distribution() function from porespy.metrics.

Best regards.
