### ISSUE TITLE
Porespy encounters an error when generating images using fractal noise, and I can't resolve it.

### ISSUE THREAD

**Issue by Maoxinmaoxin** [PMEAL/porespy#977]
I have tried installing the pyfastnoisesimd package and updating the porespy version, but I still get the TypeError: fractal_noise() got an unexpected keyword argument 'porosity'. I'm using Python version 3.11.9, my system is Windows 10 version 22H2, and my porespy version is 2.4.1. How can I solve this problem?
![微信截图_20240713192700](https://github.com/user-attachments/assets/52c2a616-4fc4-4c04-bf79-561bcb1beeeb)
![微信截图_20240713192712](https://github.com/user-attachments/assets/0ac13deb-c005-4bee-92d1-e2b92a2d68c0)

**Comment by jgostick** [comment]
As the error message says, you provided a keyword `porosity` and the function was not expecting one.  I'm guessing you are using an older version of the package but are following some documentation for a newer version. The easiest solution is to not pass `porosity` the threshold the resulting image, which will be greyscale, to get the porosity you want.

**Comment by Maoxinmaoxin** [comment]
In fact I am referring to the fractal_noise page of the official porespy documentation, which also provides the keyword porosity in the call to the function ps.generators.fractal_noise, and I have upgraded my porespy, but I still can't get this to work, which is bothering me a lot.
Also, I will try the method you provided, thank you very much.
https://porespy.org/examples/generators/reference/fractal_noise.html#fractal-noise
![微信截图_20240715225956](https://github.com/user-attachments/assets/18b8f478-ce34-4d62-afb3-08af806026e5)

**Comment by jgostick** [comment]
can you do `ps.__version__` and paste the answer here?  Also, you can always just look at the source code for this function and do the relevant steps directly.  Our function is supposed to be a convenient wrapper for the `pyfastnoisesimd` package, but it might be more convenient for you to just interact with the package directly.

**Comment by Maoxinmaoxin** [comment]
![微信截图_20240716210924](https://github.com/user-attachments/assets/36d70c26-6256-447d-b646-909a3f4a3c99)
As shown in the attached image, my PoreSpy version is 2.4.1.

Thank you very much for your patience and help!

**Comment by Maoxinmaoxin** [comment]
I will try using pyfastnoisesimd directly, but I also look forward to being able to use the `ps.generators.fractal_noise` function from the PoreSpy official documentation, which directly accepts porosity. This is very convenient, and if it's not an issue with my installation, I believe I'm not the only one facing this challenge.
