### ISSUE TITLE
Drop `dev` and develop directly on `main` to streamline workflow

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#982]
It seems there's no real benefit to having a separate `dev` branch, and it's only made the development workflow unnecessarily more complex, i.e., the extra PR from `main` to `dev` whenever we issue a new release to ensure `version.py` is up to date. It's not a big deal, but since there seems to be no real benefit, simpler is better.

@jgostick What do you think?

**Comment by jgostick** [comment]
Hmmm...the benefit of using `dev` is that code doesn't get released until we merge `dev` onto `main`, which gives a bit of a buffer to prevent immature/buggy code from being released. Is there a specific problem with the current work flow other than merging release back into dev, which I agree is awkward.

**Comment by ma-sadeghi** [comment]
Indeed it's quite a benefit to have a buffer before releasing to `pypi`. But, I've found a neat solution; Here's a screenshot of a working prototype: (basically, we can freely merge into `main`, and only trigger the deploy action on-demand with the right tag!)

<img src="https://github.com/user-attachments/assets/7c754768-f2e3-49a4-a11f-366b16985d4b" width=400px>

**Comment by jgostick** [comment]
That looks pretty great, but why have a `main` branch?  Why not just `dev`, which we release using the tag trick?  The point would be that `dev` more clearly indicates what the branch contains...a constant stream of development, punctuated with occasional tags?

**Comment by ma-sadeghi** [comment]
Yeah, I meant just have one "main" branch, it could be our `dev` since it's more descriptive. Either we can formally delete `main` or just keep it and never push to it. Does that make sense?

**Comment by ma-sadeghi** [comment]
We'd still have all our official "tags", which people can checkout in case they want a particular release.

**Comment by jgostick** [comment]
Ok, so how hard is it to implement this tag-to-release system?  And yes, I think we should drop the main branch, as crazy as that sounds.  I think dev is already the default anyway, so may actually be easier.

**Comment by ma-sadeghi** [comment]
Done in #983
